"""Generate React + Vite + TailwindCSS frontend from DoqlSpec.

Produces:
  web/
  ├── package.json
  ├── vite.config.ts
  ├── tailwind.config.js
  ├── postcss.config.js
  ├── tsconfig.json
  ├── index.html
  ├── src/
  │   ├── main.tsx
  │   ├── App.tsx           — React Router with all pages
  │   ├── api.ts            — fetch wrapper for /api/v1
  │   ├── components/
  │   │   └── Layout.tsx    — sidebar + header
  │   └── pages/
  │       ├── Dashboard.tsx
  │       └── <Entity>Page.tsx   — per-entity CRUD
  └── README.md

PWA support (optional):
  ├── public/
  │   ├── manifest.webmanifest
  │   └── sw.js
  └── src/sw-register.ts
"""
from __future__ import annotations

import pathlib
from typing import TYPE_CHECKING

from .config import (
    _gen_package_json,
    _gen_vite_config,
    _gen_tailwind_config,
    _gen_postcss_config,
    _gen_tsconfig,
    _gen_index_html,
)
from .core import _gen_main_tsx, _gen_index_css, _gen_api_ts
from .components import _gen_layout
from .pages import _gen_dashboard, _gen_entity_page
from .router import _gen_app
from .pwa import _gen_manifest, _gen_service_worker, _gen_sw_register

if TYPE_CHECKING:
    from ...parsers import DoqlSpec


def generate(spec: DoqlSpec, env_vars: dict[str, str], out: pathlib.Path) -> None:
    """Generate React + Vite + TailwindCSS frontend into *out* directory."""
    web_iface = next((i for i in spec.interfaces if i.name == "web"), None)
    if not web_iface and not spec.entities:
        (out / "README.md").write_text(
            f"# {spec.app_name} — Web\n\nNo web interface or entities defined.\n",
            encoding="utf-8",
        )
        print(f"    → web/ (no web interface, skipped)")
        return

    src = out / "src"
    components = src / "components"
    pages = src / "pages"
    for d in [src, components, pages]:
        d.mkdir(parents=True, exist_ok=True)

    web_pages = web_iface.pages if web_iface else []

    # Config files
    files = {
        "package.json":      _gen_package_json(spec),
        "vite.config.ts":    _gen_vite_config(),
        "tailwind.config.js": _gen_tailwind_config(),
        "postcss.config.js": _gen_postcss_config(),
        "tsconfig.json":     _gen_tsconfig(),
        "index.html":        _gen_index_html(spec),
    }
    for name, content in files.items():
        (out / name).write_text(content, encoding="utf-8")
        print(f"    → web/{name}")

    # Source files
    (src / "main.tsx").write_text(_gen_main_tsx(), encoding="utf-8")
    (src / "index.css").write_text(_gen_index_css(), encoding="utf-8")
    (src / "api.ts").write_text(_gen_api_ts(), encoding="utf-8")
    (src / "App.tsx").write_text(_gen_app(spec), encoding="utf-8")
    print(f"    → web/src/main.tsx, App.tsx, api.ts, index.css")

    # Layout
    (components / "Layout.tsx").write_text(
        _gen_layout(spec, web_pages, spec.entities), encoding="utf-8",
    )
    print(f"    → web/src/components/Layout.tsx")

    # Dashboard
    (pages / "Dashboard.tsx").write_text(_gen_dashboard(spec), encoding="utf-8")
    print(f"    → web/src/pages/Dashboard.tsx")

    # Entity pages
    for ent in spec.entities:
        (pages / f"{ent.name}Page.tsx").write_text(_gen_entity_page(ent), encoding="utf-8")
        print(f"    → web/src/pages/{ent.name}Page.tsx")

    # PWA support
    is_pwa = any(i.type == "pwa" for i in spec.interfaces)
    if is_pwa:
        public = out / "public"
        public.mkdir(parents=True, exist_ok=True)
        (public / "manifest.webmanifest").write_text(_gen_manifest(spec), encoding="utf-8")
        (public / "sw.js").write_text(_gen_service_worker(spec), encoding="utf-8")
        (src / "sw-register.ts").write_text(_gen_sw_register(), encoding="utf-8")
        print(f"    → web/public/manifest.webmanifest, sw.js, src/sw-register.ts")

    # README
    pwa_note = "\n\n## PWA\n\nThis app includes a service worker for offline support and background sync.\n" if is_pwa else ""
    (out / "README.md").write_text(
        f"# {spec.app_name} — Web\n\n"
        f"Generated by `doql build`. React + Vite + TailwindCSS.\n\n"
        f"## Quick start\n\n"
        f"```bash\ncd build/web\nnpm install\nnpm run dev\n```\n\n"
        f"## Pages\n\n"
        f"- **Dashboard** — entity counts overview\n"
        + "\n".join(f"- **{e.name}s** — CRUD list/create/delete" for e in spec.entities)
        + pwa_note
        + "\n",
        encoding="utf-8",
    )
    print(f"    → web/README.md")


# Re-export from submodules for backward compatibility
from .common import _snake, _kebab
from .config import (
    _gen_package_json,
    _gen_vite_config,
    _gen_tailwind_config,
    _gen_postcss_config,
    _gen_tsconfig,
    _gen_index_html,
)
from .core import _gen_main_tsx, _gen_index_css, _gen_api_ts
from .components import _gen_layout
from .pages import _gen_dashboard, _gen_entity_page, _field_input
from .router import _gen_app
from .pwa import _gen_manifest, _gen_service_worker, _gen_sw_register

__all__ = [
    "generate",
    # common
    "_snake",
    "_kebab",
    # config
    "_gen_package_json",
    "_gen_vite_config",
    "_gen_tailwind_config",
    "_gen_postcss_config",
    "_gen_tsconfig",
    "_gen_index_html",
    # core
    "_gen_main_tsx",
    "_gen_index_css",
    "_gen_api_ts",
    # components
    "_gen_layout",
    # pages
    "_gen_dashboard",
    "_gen_entity_page",
    "_field_input",
    # router
    "_gen_app",
    # pwa
    "_gen_manifest",
    "_gen_service_worker",
    "_gen_sw_register",
]
