"""PWA support generation (manifest, service worker, registration)."""
from __future__ import annotations

import json
import textwrap
from typing import TYPE_CHECKING

from .common import _snake

if TYPE_CHECKING:
    from ...parsers import DoqlSpec


def _gen_manifest(spec: DoqlSpec) -> str:
    """Generate manifest.webmanifest for PWA."""
    return json.dumps({
        "name": spec.app_name,
        "short_name": spec.app_name[:12],
        "start_url": "/",
        "display": "standalone",
        "background_color": "#ffffff",
        "theme_color": "#1e40af",
        "icons": [
            {"src": "/icon-192.png", "sizes": "192x192", "type": "image/png"},
            {"src": "/icon-512.png", "sizes": "512x512", "type": "image/png"},
        ],
    }, indent=2)


def _gen_service_worker(spec: DoqlSpec) -> str:
    """Generate sw.js service worker with caching and background sync."""
    cache_name = _snake(spec.app_name) + "-v" + spec.version.replace(".", "-")
    return textwrap.dedent(f'''\
        // Service Worker — generated by doql
        const CACHE_NAME = "{cache_name}";
        const PRECACHE_URLS = [
          "/",
          "/index.html",
          "/manifest.webmanifest",
        ];

        self.addEventListener("install", (event) => {{
          event.waitUntil(
            caches.open(CACHE_NAME).then((cache) => cache.addAll(PRECACHE_URLS))
          );
          self.skipWaiting();
        }});

        self.addEventListener("activate", (event) => {{
          event.waitUntil(
            caches.keys().then((names) =>
              Promise.all(
                names.filter((n) => n !== CACHE_NAME).map((n) => caches.delete(n))
              )
            )
          );
          self.clients.claim();
        }});

        self.addEventListener("fetch", (event) => {{
          if (event.request.method !== "GET") return;
          // Network-first for API, cache-first for static
          if (event.request.url.includes("/api/")) {{
            event.respondWith(
              fetch(event.request)
                .then((resp) => {{
                  const clone = resp.clone();
                  caches.open(CACHE_NAME).then((c) => c.put(event.request, clone));
                  return resp;
                }})
                .catch(() => caches.match(event.request))
            );
          }} else {{
            event.respondWith(
              caches.match(event.request).then((cached) => cached || fetch(event.request))
            );
          }}
        }});

        // Background sync for offline mutations
        self.addEventListener("sync", (event) => {{
          if (event.tag === "sync-mutations") {{
            event.waitUntil(syncOfflineMutations());
          }}
        }});

        async function syncOfflineMutations() {{
          // Retrieve queued mutations from IndexedDB and replay them
          // This is a stub — integrate with your offline queue
          console.log("[SW] Syncing offline mutations...");
        }}
    ''')


def _gen_sw_register() -> str:
    """Generate sw-register.ts for service worker registration."""
    return textwrap.dedent('''\
        // SW registration — generated by doql
        export function registerSW() {
          if ("serviceWorker" in navigator) {
            window.addEventListener("load", () => {
              navigator.serviceWorker
                .register("/sw.js")
                .then((reg) => console.log("SW registered:", reg.scope))
                .catch((err) => console.warn("SW registration failed:", err));
            });
          }
        }
    ''')
