"""FastAPI + SQLAlchemy backend generator from DoqlSpec.

This package generates a complete FastAPI backend:
  - database.py       — SQLAlchemy engine + session
  - models.py         — ORM models from ENTITY
  - schemas.py        — Pydantic request/response schemas
  - routes.py         — CRUD endpoints for each ENTITY
  - auth.py           — JWT authentication (optional)
  - alembic/          — Database migrations
  - main.py           — FastAPI app entry point
  - requirements.txt  — Dependencies

The generator has been refactored from a monolithic module into
focused submodules to reduce cyclomatic complexity.
"""
from __future__ import annotations

import json
import pathlib
from typing import IO, TYPE_CHECKING

from .common import snake
from .database import gen_database
from .models import gen_models
from .schemas import gen_schemas
from .routes import gen_routes
from .auth import gen_auth
from .alembic import gen_alembic_ini, gen_alembic_env, gen_initial_migration
from .main import gen_main, gen_requirements

if TYPE_CHECKING:
    from ...parsers.models import DoqlSpec


def _write_api_files(out: pathlib.Path, spec: DoqlSpec, env_vars: dict[str, str], has_auth: bool) -> None:
    """Write API layer files."""
    files = {
        "main.py":          gen_main(spec),
        "database.py":      gen_database(spec, env_vars),
        "models.py":        gen_models(spec),
        "schemas.py":       gen_schemas(spec),
        "routes.py":        gen_routes(spec),
        "requirements.txt": gen_requirements(has_auth=has_auth),
    }
    if has_auth:
        files["auth.py"] = gen_auth(spec)

    for name, content in files.items():
        (out / name).write_text(content, encoding="utf-8")
        print(f"    → api/{name}")


def _write_alembic_files(out: pathlib.Path, spec: DoqlSpec) -> None:
    """Write Alembic migration files."""
    alembic_dir = out / "alembic" / "versions"
    alembic_dir.mkdir(parents=True, exist_ok=True)
    (out / "alembic.ini").write_text(gen_alembic_ini(), encoding="utf-8")
    (out / "alembic" / "env.py").write_text(gen_alembic_env(), encoding="utf-8")
    (alembic_dir / "001_initial.py").write_text(gen_initial_migration(spec), encoding="utf-8")
    print(f"    → api/alembic.ini, alembic/env.py, alembic/versions/001_initial.py")


def _write_api_readme(out: pathlib.Path, spec: DoqlSpec) -> None:
    """Write API README.md."""
    readme = out / "README.md"
    readme.write_text(
        f"# {spec.app_name} — API\n\n"
        f"Generated by `doql build`.\n\n"
        f"## Quick start\n\n"
        f"```bash\n"
        f"cd build/api\n"
        f"pip install -r requirements.txt\n"
        f"uvicorn main:app --reload\n"
        f"```\n\n"
        f"## Entities\n\n"
        + "\n".join(f"- **{e.name}** ({len(e.fields)} fields)" for e in spec.entities)
        + "\n\n"
        f"## Endpoints\n\n"
        + "\n".join(
            f"- `GET /api/v1/{snake(e.name)}s` · `POST` · `GET /:id` · `PATCH /:id` · `DELETE /:id`"
            for e in spec.entities
        )
        + "\n",
        encoding="utf-8",
    )
    print(f"    → api/README.md")


def generate(spec: DoqlSpec, env_vars: dict[str, str], out: pathlib.Path) -> None:
    """Generate API layer files into *out* directory."""
    if not spec.entities:
        readme = out / "README.md"
        readme.write_text(
            f"# {spec.app_name} — API\n\nNo entities defined — skipping code generation.\n",
            encoding="utf-8",
        )
        print(f"    → api/ (no entities, skipped)")
        return

    has_auth = bool(spec.roles)
    _write_api_files(out, spec, env_vars, has_auth)
    _write_alembic_files(out, spec)
    _write_api_readme(out, spec)


def export_openapi(spec: DoqlSpec, out: IO[str]) -> None:
    """Write OpenAPI 3.1 JSON to the given stream."""
    paths = {}
    for e in spec.entities:
        plural = snake(e.name) + "s"
        base = f"/api/v1/{plural}"
        paths[base] = {
            "get": {
                "summary": f"List {e.name}s",
                "responses": {"200": {"description": "OK"}},
            },
            "post": {
                "summary": f"Create {e.name}",
                "responses": {"201": {"description": "Created"}},
            },
        }
        paths[f"{base}/{{id}}"] = {
            "get":    {"summary": f"Get {e.name}", "responses": {"200": {"description": "OK"}}},
            "patch":  {"summary": f"Update {e.name}", "responses": {"200": {"description": "OK"}}},
            "delete": {"summary": f"Delete {e.name}", "responses": {"204": {"description": "No Content"}}},
        }

    openapi = {
        "openapi": "3.1.0",
        "info": {"title": spec.app_name, "version": spec.version},
        "paths": paths,
    }
    json.dump(openapi, out, indent=2)


# Re-export from submodules for backward compatibility
from .common import (
    TYPE_MAP,
    sa_type,
    py_type,
    py_default,
    safe_name,
    snake,
)
from .database import gen_database
from .models import gen_models
from .schemas import gen_schemas
from .routes import gen_routes
from .auth import gen_auth
from .alembic import (
    gen_alembic_ini,
    gen_alembic_env,
    gen_initial_migration,
)
from .main import gen_main, gen_requirements

__all__ = [
    "generate",
    "export_openapi",
    # common
    "TYPE_MAP",
    "sa_type",
    "py_type",
    "py_default",
    "safe_name",
    "snake",
    # submodules
    "gen_database",
    "gen_models",
    "gen_schemas",
    "gen_routes",
    "gen_auth",
    "gen_alembic_ini",
    "gen_alembic_env",
    "gen_initial_migration",
    "gen_main",
    "gen_requirements",
]
