"""Alembic migration configuration generation."""
from __future__ import annotations

import textwrap
from typing import TYPE_CHECKING

from .common import sa_type, safe_name, snake

if TYPE_CHECKING:
    from ...parsers.models import DoqlSpec


def gen_alembic_ini() -> str:
    """Generate alembic.ini configuration file."""
    return textwrap.dedent("""\
        # Alembic config — generated by doql
        [alembic]
        script_location = alembic
        sqlalchemy.url = sqlite:///./data.db

        [loggers]
        keys = root,sqlalchemy,alembic

        [handlers]
        keys = console

        [formatters]
        keys = generic

        [logger_root]
        level = WARN
        handlers = console

        [logger_sqlalchemy]
        level = WARN
        handlers =
        qualname = sqlalchemy.engine

        [logger_alembic]
        level = INFO
        handlers =
        qualname = alembic

        [handler_console]
        class = StreamHandler
        args = (sys.stderr,)
        level = NOTSET
        formatter = generic

        [formatter_generic]
        format = %(levelname)-5.5s [%(name)s] %(message)s
    """)


def gen_alembic_env() -> str:
    """Generate alembic/env.py migration environment."""
    return (
        '# Alembic env.py — generated by doql\n'
        'from logging.config import fileConfig\n'
        'from alembic import context\n'
        'from sqlalchemy import engine_from_config, pool\n'
        'import sys, os\n'
        '\n'
        'sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))\n'
        'from database import Base\n'
        'import models  # noqa: F401\n'
        '\n'
        'config = context.config\n'
        'if config.config_file_name:\n'
        '    fileConfig(config.config_file_name)\n'
        '\n'
        'target_metadata = Base.metadata\n'
        '\n'
        '\n'
        'def run_migrations_offline():\n'
        '    url = config.get_main_option("sqlalchemy.url")\n'
        '    context.configure(url=url, target_metadata=target_metadata, literal_binds=True)\n'
        '    with context.begin_transaction():\n'
        '        context.run_migrations()\n'
        '\n'
        '\n'
        'def run_migrations_online():\n'
        '    connectable = engine_from_config(\n'
        '        config.get_section(config.config_ini_section),\n'
        '        prefix="sqlalchemy.",\n'
        '        poolclass=pool.NullPool,\n'
        '    )\n'
        '    with connectable.connect() as connection:\n'
        '        context.configure(connection=connection, target_metadata=target_metadata)\n'
        '        with context.begin_transaction():\n'
        '            context.run_migrations()\n'
        '\n'
        '\n'
        'if context.is_offline_mode():\n'
        '    run_migrations_offline()\n'
        'else:\n'
        '    run_migrations_online()\n'
    )


def gen_initial_migration(spec: DoqlSpec) -> str:
    """Generate initial Alembic migration with all tables."""
    lines = [
        '"""Initial migration — generated by doql."""',
        'revision = "001"',
        'down_revision = None',
        '',
        'from alembic import op',
        'import sqlalchemy as sa',
        '',
        '',
        'def upgrade():',
    ]

    for ent in spec.entities:
        table = snake(ent.name) + "s"
        lines.append(f'    op.create_table(')
        lines.append(f'        "{table}",')

        has_id = any(f.name == "id" for f in ent.fields)
        if not has_id:
            lines.append(f'        sa.Column("id", sa.String(36), primary_key=True),')

        for f in ent.fields:
            if f.computed:
                continue

            sa_type_str = sa_type(f)
            col_args = []
            if f.name == "id":
                col_args.append("primary_key=True")
            if f.unique:
                col_args.append("unique=True")
            if not f.required and f.name != "id":
                col_args.append("nullable=True")

            args_str = ", ".join(col_args)
            if args_str:
                lines.append(f'        sa.Column("{safe_name(f.name)}", sa.{sa_type_str}, {args_str}),')
            else:
                lines.append(f'        sa.Column("{safe_name(f.name)}", sa.{sa_type_str}),')

        lines.append(f'    )')

    lines.append('')
    lines.append('')
    lines.append('def downgrade():')

    for ent in reversed(spec.entities):
        table = snake(ent.name) + "s"
        lines.append(f'    op.drop_table("{table}")')

    lines.append('')
    return "\n".join(lines)
