"""Database configuration generation for FastAPI backend."""
from __future__ import annotations

import textwrap
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ...parsers.models import DoqlSpec


def gen_database(spec: DoqlSpec, env_vars: dict[str, str]) -> str:
    """Generate database.py with SQLAlchemy engine and session."""
    db_url = env_vars.get("DATABASE_URL", "sqlite:///./data/app.db")
    return textwrap.dedent(f'''\
        """Database engine and session — generated by doql."""
        import pathlib
        from sqlalchemy import create_engine
        from sqlalchemy.orm import sessionmaker, DeclarativeBase

        DATABASE_URL = "{db_url}"

        if DATABASE_URL.startswith("sqlite:///"):
            _db_path = pathlib.Path(DATABASE_URL[len("sqlite:///"):])
            _db_path.parent.mkdir(parents=True, exist_ok=True)

        engine = create_engine(DATABASE_URL, connect_args={{"check_same_thread": False}} if "sqlite" in DATABASE_URL else {{}})
        SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)


        class Base(DeclarativeBase):
            pass


        def get_db():
            db = SessionLocal()
            try:
                yield db
            finally:
                db.close()
    ''')
