"""FastAPI main application generation."""
from __future__ import annotations

import textwrap
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ...parsers.models import DoqlSpec


def gen_main(spec: DoqlSpec) -> str:
    """Generate FastAPI main application file."""
    return textwrap.dedent(f'''\
        """FastAPI application — generated by doql."""
        from contextlib import asynccontextmanager
        from fastapi import FastAPI
        from fastapi.middleware.cors import CORSMiddleware
        from database import engine, Base
        from routes import router

        @asynccontextmanager
        async def lifespan(app: FastAPI):
            Base.metadata.create_all(bind=engine)
            yield

        app = FastAPI(
            title="{spec.app_name}",
            version="{spec.version}",
            lifespan=lifespan,
        )

        app.add_middleware(
            CORSMiddleware,
            allow_origins=["*"],
            allow_credentials=True,
            allow_methods=["*"],
            allow_headers=["*"],
        )

        app.include_router(router)

        try:
            from auth import router as auth_router, User as AuthUser  # noqa: F401
            app.include_router(auth_router)
        except ImportError:
            pass


        @app.get("/health")
        def health():
            return {{"status": "ok", "app": "{spec.app_name}", "version": "{spec.version}"}}
    ''')


def gen_requirements(has_auth: bool = False) -> str:
    """Generate requirements.txt with pinned dependencies."""
    lines = [
        "fastapi>=0.104",
        "uvicorn[standard]>=0.24",
        "sqlalchemy>=2.0",
        "alembic>=1.13",
        "pydantic>=2.0",
        "python-dotenv>=1.0",
    ]
    if has_auth:
        lines += [
            "python-jose[cryptography]>=3.3",
            "passlib>=1.7",
            # Pin bcrypt < 4.1 — passlib <=1.7.4 breaks on bcrypt 4.1+
            # due to the removal of the internal `__about__` attribute.
            "bcrypt>=4.0,<4.1",
            "python-multipart>=0.0.6",
        ]
    return "\n".join(lines) + "\n"
