"""SQLAlchemy ORM models generation for FastAPI backend."""
from __future__ import annotations

from typing import TYPE_CHECKING

from .common import sa_type, safe_name, snake

if TYPE_CHECKING:
    from ...parsers.models import DoqlSpec


def gen_models(spec: DoqlSpec) -> str:
    """Generate SQLAlchemy ORM models from DoqlSpec.

    Reduces complexity by delegating field generation to helper.
    """
    # Set of entity names actually present in the spec — used to drop
    # dangling foreign-key references to undefined entities.
    known_entities = {e.name for e in spec.entities}
    lines = [
        '"""SQLAlchemy ORM models — generated by doql."""',
        "from sqlalchemy import Column, String, Integer, Float, Boolean, Text, Date, DateTime, JSON, ForeignKey",
        "from sqlalchemy.orm import relationship",
        "from database import Base",
        "",
    ]

    for ent in spec.entities:
        table = snake(ent.name) + "s"
        lines.append("")
        lines.append(f"class {ent.name}(Base):")
        lines.append(f'    __tablename__ = "{table}"')
        lines.append("")

        # Auto-inject a primary key column when the entity has no `id` field
        has_id = any(f.name == "id" for f in ent.fields)
        if not has_id:
            lines.append(f'    id = Column(String(36), primary_key=True)')

        # Generate field columns using helper to reduce per-field complexity
        for f in ent.fields:
            if f.computed:
                continue
            col_def = _gen_column_def(f, known_entities)
            lines.append(col_def)

        lines.append("")

    return "\n".join(lines)


def _gen_column_def(f, known_entities: set[str]) -> str:
    """Generate a single SQLAlchemy Column definition.

    Isolated to reduce cyclomatic complexity of the main loop.
    """
    from ...parsers.models import EntityField
    f: EntityField

    # Positional args first, then keyword args
    pos_args = [sa_type(f)]
    if f.ref and f.ref in known_entities:
        fk_table = snake(f.ref) + "s"
        pos_args.append(f'ForeignKey("{fk_table}.id")')
    # If f.ref points to an undefined entity, silently degrade to a
    # plain String column (still holds the referenced id as text).

    kw_args: list[str] = []
    if f.name == "id":
        kw_args.append("primary_key=True")
    if f.unique:
        kw_args.append("unique=True")
    if not f.required and f.name != "id":
        kw_args.append("nullable=True")
    if f.default and f.type in ("int", "float", "bool"):
        val = f.default
        if f.type == "bool":
            val = val.lower() in ("true", "1", "yes")
        kw_args.append(f"default={val}")

    all_args = pos_args + kw_args
    return f"    {safe_name(f.name)} = Column({', '.join(all_args)})"
