"""CRUD routes generation for FastAPI backend."""
from __future__ import annotations

from typing import TYPE_CHECKING

from .common import snake

if TYPE_CHECKING:
    from ...parsers.models import DoqlSpec


def gen_routes(spec: DoqlSpec) -> str:
    """Generate CRUD routes for all entities in the spec."""
    lines = [
        '"""CRUD routes — generated by doql."""',
        "from fastapi import APIRouter, Depends, HTTPException",
        "from sqlalchemy.orm import Session",
        "from database import get_db",
        "import models",
        "import schemas",
        "",
        "router = APIRouter(prefix='/api/v1')",
        "",
    ]

    for ent in spec.entities:
        lines.extend(_gen_entity_routes(ent))

    return "\n".join(lines)


def _gen_entity_routes(ent) -> list[str]:
    """Generate all CRUD routes for a single entity."""
    name = ent.name
    lower = snake(name)
    plural = lower + "s"

    lines = [f"# ── {name} ──", ""]
    lines.extend(_gen_list_route(name, plural))
    lines.extend(_gen_get_route(name, lower, plural))
    lines.extend(_gen_create_route(name, lower, plural))
    lines.extend(_gen_update_route(name, lower, plural))
    lines.extend(_gen_delete_route(name, lower, plural))
    return lines


def _gen_list_route(name: str, plural: str) -> list[str]:
    """Generate LIST route."""
    return [
        f'@router.get("/{plural}", response_model=list[schemas.{name}Response])',
        f"def list_{plural}(skip: int = 0, limit: int = 100, db: Session = Depends(get_db)):",
        f"    return db.query(models.{name}).offset(skip).limit(limit).all()",
        "",
    ]


def _gen_get_route(name: str, lower: str, plural: str) -> list[str]:
    """Generate GET by id route."""
    return [
        f'@router.get("/{plural}/{{item_id}}", response_model=schemas.{name}Response)',
        f"def get_{lower}(item_id: str, db: Session = Depends(get_db)):",
        f"    obj = db.query(models.{name}).filter(models.{name}.id == item_id).first()",
        "    if not obj:",
        f'        raise HTTPException(404, "{name} not found")',
        "    return obj",
        "",
    ]


def _gen_create_route(name: str, lower: str, plural: str) -> list[str]:
    """Generate CREATE route."""
    return [
        f'@router.post("/{plural}", response_model=schemas.{name}Response, status_code=201)',
        f"def create_{lower}(data: schemas.{name}Create, db: Session = Depends(get_db)):",
        "    import uuid as _uuid",
        "    payload = data.model_dump()",
        "    payload.setdefault('id', str(_uuid.uuid4()))",
        f"    obj = models.{name}(**payload)",
        "    db.add(obj)",
        "    db.commit()",
        "    db.refresh(obj)",
        "    return obj",
        "",
    ]


def _gen_update_route(name: str, lower: str, plural: str) -> list[str]:
    """Generate UPDATE route."""
    return [
        f'@router.patch("/{plural}/{{item_id}}", response_model=schemas.{name}Response)',
        f"def update_{lower}(item_id: str, data: schemas.{name}Update, db: Session = Depends(get_db)):",
        f"    obj = db.query(models.{name}).filter(models.{name}.id == item_id).first()",
        "    if not obj:",
        f'        raise HTTPException(404, "{name} not found")',
        "    for key, val in data.model_dump(exclude_unset=True).items():",
        "        setattr(obj, key, val)",
        "    db.commit()",
        "    db.refresh(obj)",
        "    return obj",
        "",
    ]


def _gen_delete_route(name: str, lower: str, plural: str) -> list[str]:
    """Generate DELETE route."""
    return [
        f'@router.delete("/{plural}/{{item_id}}", status_code=204)',
        f"def delete_{lower}(item_id: str, db: Session = Depends(get_db)):",
        f"    obj = db.query(models.{name}).filter(models.{name}.id == item_id).first()",
        "    if not obj:",
        f'        raise HTTPException(404, "{name} not found")',
        "    db.delete(obj)",
        "    db.commit()",
        "",
    ]
