"""Pydantic schemas generation for FastAPI backend.

Splits the high-complexity schema generation into focused helpers
to reduce cyclomatic complexity from 22 to ~5 per function.
"""
from __future__ import annotations

from typing import TYPE_CHECKING

from .common import py_type, py_default, safe_name, TYPE_MAP

if TYPE_CHECKING:
    from ...parsers.models import DoqlSpec, Entity, EntityField


def gen_schemas(spec: DoqlSpec) -> str:
    """Generate Pydantic schemas from DoqlSpec using delegation pattern."""
    lines = [
        '"""Pydantic schemas — generated by doql."""',
        "from __future__ import annotations",
        "from datetime import date, datetime",
        "from typing import Optional",
        "from pydantic import BaseModel",
        "",
    ]

    for ent in spec.entities:
        lines.extend(_gen_entity_schemas(ent))

    return "\n".join(lines)


def _gen_entity_schemas(ent: Entity) -> list[str]:
    """Generate all three schemas (Create, Response, Update) for one entity."""
    lines = []
    lines.extend(_gen_create_schema(ent))
    lines.extend(_gen_response_schema(ent))
    lines.extend(_gen_update_schema(ent))
    lines.append("")
    return lines


def _gen_create_schema(ent: Entity) -> list[str]:
    """Generate Create schema (no id, no computed fields)."""
    lines = [f"", f"class {ent.name}Create(BaseModel):"]
    create_fields = [f for f in ent.fields if not f.auto and not f.computed]
    if not create_fields:
        lines.append("    pass")
    for f in create_fields:
        lines.append(f"    {safe_name(f.name)}: {py_type(f)}{py_default(f)}")
    return lines


def _gen_response_schema(ent: Entity) -> list[str]:
    """Generate Response schema (all fields, auto-inject id if missing)."""
    lines = [f"", f"class {ent.name}Response(BaseModel):"]
    lines.append("    model_config = {'from_attributes': True}")

    has_id = any(f.name == "id" for f in ent.fields)
    if not has_id:
        lines.append("    id: Optional[str] = None")

    resp_fields = [f for f in ent.fields if not f.computed]
    if not resp_fields and has_id:
        lines.append("    pass")

    for f in resp_fields:
        default = " = None" if f.auto or not f.required else ""
        lines.append(f"    {safe_name(f.name)}: {py_type(f)}{default}")

    return lines


def _gen_update_schema(ent: Entity) -> list[str]:
    """Generate Update schema (all optional except id/computed)."""
    lines = [f"", f"class {ent.name}Update(BaseModel):"]
    update_fields = [f for f in ent.fields if not f.auto and not f.computed and f.name != "id"]
    if not update_fields:
        lines.append("    pass")
    for f in update_fields:
        base_type = TYPE_MAP.get(f.type, ("", "str"))[1]
        lines.append(f"    {safe_name(f.name)}: Optional[{base_type}] = None")
    return lines
