// Generated by doql build — Jenkins pipeline
pipeline {
    agent any
    stages {
        stage('Validate') {
            steps {
                sh 'pip install doql && doql validate'
            }
        }
        stage('Build') {
            steps {
                sh 'pip install doql && doql build --force'
            }
        }
        stage('API Smoke Test') {
            steps {
                dir('build/api') {
                    sh 'pip install -r requirements.txt || true'
                    sh 'python -c "from main import app; print(\'API import OK\')"'
                }
            }
        }
        stage('Web Build') {
            agent { label 'nodejs' }
            steps {
                dir('build/web') {
                    sh 'npm install || true'
                    sh 'npm run build || true'
                }
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}
