"""Code generation utilities — shared patterns for writing generated code."""
from __future__ import annotations

import pathlib
from typing import Callable


def write_code_block(content: str, path: str | pathlib.Path) -> None:
    """Write a code block to file, creating parent directories if needed.
    
    This utility replaces the repetitive pattern of:
    - Creating parent directories
    - Writing text content
    - Handling encoding
    
    Used across generators to reduce duplication.
    """
    path = pathlib.Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def generate_file_from_template(
    template_name: str,
    variables: dict[str, str],
    output_path: str | pathlib.Path,
) -> None:
    """Generate a file from a template with variable substitution.
    
    Template variables use {{VAR_NAME}} syntax.
    """
    from jinja2 import Template
    
    # For now, use inline templates. In future, load from doql/templates/
    templates: dict[str, str] = {
        "build_rs": '''use std::env;
use std::path::PathBuf;

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
}
''',
        "readme_md": '''# {{PROJECT_NAME}}

Generated by doql.
''',
    }
    
    template_str = templates.get(template_name, "")
    if not template_str:
        raise ValueError(f"Unknown template: {template_name}")
    
    content = Template(template_str).render(**variables)
    write_code_block(content, output_path)


# Backward-compatible alias for existing code
_gen_build_rs = lambda path: write_code_block(
    '''use std::env;
use std::path::PathBuf;

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
}
''',
    path
)
