"""Adopt a live device into ``.doql.less`` via op3.

This module implements the device side of ``doql adopt`` — it sits next to
the existing directory scanner (:mod:`doql.adopt.scanner`) but replaces the
filesystem walk with an op3 scan over SSH (or any other
:class:`opstree.ProbeContext`).

Public surface
--------------

``adopt_from_device(target, ...) -> str``
    Scan the device, render the resulting :class:`opstree.Snapshot` as
    ``.doql.less`` text, and optionally write it to disk.

``adopt_from_device_to_snapshot(target, ...) -> Snapshot``
    Lower-level helper that returns the raw op3 snapshot — useful for
    callers that want to render multiple formats or post-process before
    emitting.
"""
from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING, Callable

from ..integrations.op3_bridge import (
    DEFAULT_ADOPT_LAYERS,
    make_scanner,
    make_ssh_context,
    require_op3,
    snapshot_to_less,
)

if TYPE_CHECKING:  # pragma: no cover
    from opstree.probes.context import ProbeContext
    from opstree.snapshot.model import Snapshot


# ``scope`` argument forwarded to ``LessAdapter.render``. ``service`` and
# ``runtime`` give the minimum viable ``.doql.less`` — physical/endpoint
# sections are added on top when the matching layers were scanned.
_DEFAULT_RENDER_SCOPE: tuple[str, ...] = ("service", "runtime", "endpoint", "physical")


def _header(target: str, snapshot: "Snapshot", layers: list[str]) -> str:
    """Return a ``.doql.less`` provenance header."""
    return (
        "// Auto-generated by `doql adopt --from-device`\n"
        f"// Source: {target}\n"
        f"// Scanned at: {snapshot.scanned_at.isoformat()}\n"
        f"// Scanner: op3 {snapshot.scanner_version}\n"
        f"// Layers: {', '.join(layers)}\n"
        "\n"
    )


def adopt_from_device_to_snapshot(
    target: str,
    *,
    ssh_key: str | None = None,
    layers: list[str] | tuple[str, ...] | None = None,
    context_factory: Callable[[], "ProbeContext"] | None = None,
) -> "Snapshot":
    """Scan ``target`` via op3 and return a raw :class:`Snapshot`.

    Parameters
    ----------
    target:
        SSH target in the ``user@host`` form, or any string the chosen
        ``context_factory`` understands. Used verbatim as the snapshot's
        target identifier.
    ssh_key:
        Optional path to an SSH private key, forwarded to
        :class:`opstree.SSHContext`. Ignored when ``context_factory`` is
        provided.
    layers:
        Layer ids to probe. Defaults to
        :data:`doql.integrations.op3_bridge.DEFAULT_ADOPT_LAYERS`;
        dependencies are resolved automatically.
    context_factory:
        Test seam — a zero-argument callable that returns a
        :class:`opstree.ProbeContext`. When omitted, a real SSH context is
        created. This lets tests inject
        :class:`opstree.probes.context.MockContext` without monkey-patching
        ``paramiko`` / ``subprocess``.
    """
    require_op3("doql adopt --from-device")

    ctx = context_factory() if context_factory is not None else make_ssh_context(
        target=target, ssh_key=ssh_key,
    )
    scanner = make_scanner(layers)
    return scanner.scan(target, ctx.execute)


def adopt_from_device(
    target: str,
    *,
    ssh_key: str | None = None,
    layers: list[str] | tuple[str, ...] | None = None,
    output: Path | None = None,
    render_scope: list[str] | tuple[str, ...] | None = None,
    context_factory: Callable[[], "ProbeContext"] | None = None,
) -> str:
    """Scan ``target`` and return ``.doql.less`` text (optionally writing it).

    See :func:`adopt_from_device_to_snapshot` for parameter details. The
    extra ``output`` and ``render_scope`` arguments control the emission
    step.
    """
    snapshot = adopt_from_device_to_snapshot(
        target,
        ssh_key=ssh_key,
        layers=layers,
        context_factory=context_factory,
    )

    effective_layers = list(layers) if layers else list(DEFAULT_ADOPT_LAYERS)
    scope = list(render_scope) if render_scope else list(_DEFAULT_RENDER_SCOPE)

    body = snapshot_to_less(snapshot, scope=scope)
    result = _header(target, snapshot, effective_layers) + body

    if output is not None:
        Path(output).write_text(result, encoding="utf-8")

    return result


__all__ = [
    "adopt_from_device",
    "adopt_from_device_to_snapshot",
]
