"""Automatic fixes for common doctor issues."""
from __future__ import annotations

import pathlib

from ....parsers.models import DoqlSpec
from .report import DoctorReport


def _apply_fixes(report: DoctorReport, root: pathlib.Path, spec: DoqlSpec) -> None:
    """Apply automatic fixes for common issues."""
    print("\n🔧 Applying fixes...\n")

    for check in report.checks:
        if check.status != "warn":
            continue

        # Fix 1: Missing .env file
        if check.name == "env-file" and "missing" in check.message.lower():
            env_file = root / ".env"
            template = root / ".env.example"
            if template.exists():
                env_file.write_text(template.read_text())
                print(f"  ✅ Created {env_file} from .env.example")
            else:
                # Create minimal .env from spec.env_refs
                env_content = "# Generated by doql doctor --fix\n"
                for ref in spec.env_refs:
                    env_content += f"{ref}=PLACEHOLDER\n"
                env_file.write_text(env_content)
                print(f"  ✅ Created {env_file} with placeholder values")

        # Fix 2: Missing migration.yaml
        if check.name == "migration.yaml":
            print("  ⚠️  Run 'doql build' to generate migration.yaml")

        # Fix 3: Deprecated deploy strategy names
        if check.name == "deploy" and spec.deploy.target:
            deprecated_map = {
                "docker-compose": "docker_full",
                "quadlet": "podman_quadlet",
                "kubernetes": "k3s",
            }
            if spec.deploy.target in deprecated_map:
                canonical = deprecated_map[spec.deploy.target]
                print(f"  ⚠️  Update DEPLOY.target from '{spec.deploy.target}' to '{canonical}'")

    print("\n🔧 Fixes applied. Run 'doql doctor' again to verify.")

    print(f"\n  {report.ok} ok, {report.warnings} warning(s), {report.failures} failure(s)")
