"""End-to-end tests for ``doql adopt --from-device``.

We can't (and don't want to) SSH to a real device in CI. Instead we inject
an :class:`opstree.MockContext` via the ``context_factory`` hook and
verify that the full pipeline — scan → render → write — produces a usable
``.doql.less`` file.
"""
from __future__ import annotations

import argparse
from pathlib import Path

import pytest

pytest.importorskip("opstree")

from doql.adopt.device_scanner import (  # noqa: E402  (after importorskip)
    adopt_from_device,
    adopt_from_device_to_snapshot,
)
from doql.cli.commands.adopt import cmd_adopt  # noqa: E402
from doql.integrations.op3_bridge import make_mock_context  # noqa: E402


# ── fixture helpers ───────────────────────────────────────────────────────


def _healthy_rpi_responses() -> dict[str, tuple[str, str, int]]:
    """Minimal set of SSH responses to satisfy the default adopt layers.

    Covers runtime (docker present, one container), service
    (``nginx.service`` running), and leaves endpoint/business probes to
    report graceful "unknown" results.
    """
    return {
        # runtime.container
        "which docker": ("/usr/bin/docker", "", 0),
        "which podman": ("", "", 1),
        "docker --version 2>/dev/null": ("Docker version 24.0.7, build afdd53b", "", 0),
        "podman --version 2>/dev/null": ("", "", 1),
        "docker ps -a --format json 2>/dev/null": (
            '[{"ID":"deadbeef1234","Names":"web","Image":"nginx:1.25",'
            '"State":"running","Status":"Up 3 hours","Labels":{}}]',
            "", 0,
        ),
        "podman ps -a --format json 2>/dev/null": ("", "", 1),
        # service.containers
        "which systemctl": ("/bin/systemctl", "", 0),
        "systemctl list-units --type=service --all --no-legend 2>/dev/null": (
            "nginx.service   loaded active running nginx web server\n"
            "sshd.service    loaded active running OpenSSH server\n",
            "", 0,
        ),
        "systemctl is-enabled nginx.service 2>/dev/null": ("enabled", "", 0),
        "systemctl is-enabled sshd.service 2>/dev/null": ("enabled", "", 0),
    }


# ── functional API ────────────────────────────────────────────────────────


def test_adopt_from_device_returns_less_text():
    ctx = make_mock_context(_healthy_rpi_responses())
    text = adopt_from_device(
        target="pi@fake.local",
        layers=["service.containers"],
        context_factory=lambda: ctx,
    )

    # Provenance header.
    assert "Auto-generated by `doql adopt --from-device`" in text
    assert "Source: pi@fake.local" in text
    assert "Scanner: op3" in text

    # Body contains the scanned service.
    assert 'service[name="nginx.service"]' in text


def test_adopt_from_device_writes_output(tmp_path: Path):
    ctx = make_mock_context(_healthy_rpi_responses())
    out = tmp_path / "generated.doql.less"

    text = adopt_from_device(
        target="pi@fake.local",
        layers=["service.containers"],
        output=out,
        context_factory=lambda: ctx,
    )

    assert out.exists()
    assert out.read_text(encoding="utf-8") == text
    assert out.stat().st_size > 0


def test_adopt_from_device_to_snapshot_contains_layer_data():
    ctx = make_mock_context(_healthy_rpi_responses())
    snapshot = adopt_from_device_to_snapshot(
        target="pi@fake.local",
        layers=["service.containers"],
        context_factory=lambda: ctx,
    )

    services = snapshot.layer("service.containers")
    assert services is not None
    names = {s["name"] for s in services.data["systemd_services"]}
    assert "nginx.service" in names
    assert "sshd.service" in names


def test_adopt_output_is_parsable_by_doql(tmp_path: Path):
    """Contract test: the LESS we emit must round-trip through doql's
    own parser without an error-level diagnostic."""
    from doql.parsers import parse_file

    ctx = make_mock_context(_healthy_rpi_responses())
    out = tmp_path / "app.doql.less"
    adopt_from_device(
        target="pi@fake.local",
        layers=["service.containers"],
        output=out,
        context_factory=lambda: ctx,
    )

    spec = parse_file(out)
    assert not [i for i in spec.parse_errors if i.severity == "error"], (
        f"doql could not parse op3-generated LESS: {spec.parse_errors}"
    )


# ── CLI wiring ────────────────────────────────────────────────────────────


def _make_cli_args(**overrides) -> argparse.Namespace:
    """Build a namespace that matches what ``create_parser`` produces."""
    defaults = dict(
        target=None,
        output=None,
        format="less",
        force=False,
        from_device="pi@fake.local",
        ssh_key=None,
        layers=["service.containers"],
    )
    defaults.update(overrides)
    return argparse.Namespace(**defaults)


def test_cmd_adopt_from_device_writes_file(tmp_path: Path, monkeypatch,
                                           capsys: pytest.CaptureFixture[str]):
    """``cmd_adopt`` should delegate to the device scanner and return 0."""
    out = tmp_path / "app.doql.less"
    ctx = make_mock_context(_healthy_rpi_responses())

    # Inject our MockContext by patching the ``adopt_from_device`` symbol
    # that the CLI command imports. We import it *inside* the function
    # under test (``_cmd_adopt_from_device``), so patching the source
    # module is enough.
    from doql.adopt import device_scanner

    real = device_scanner.adopt_from_device

    def _patched(**kw):
        kw.setdefault("context_factory", lambda: ctx)
        return real(**kw)

    monkeypatch.setattr(device_scanner, "adopt_from_device", _patched)

    args = _make_cli_args(output=str(out))
    rc = cmd_adopt(args)

    captured = capsys.readouterr()
    assert rc == 0, captured
    assert out.exists()
    assert "Scanning device pi@fake.local" in captured.out
    assert "Written" in captured.out


def test_cmd_adopt_rejects_non_less_format(capsys: pytest.CaptureFixture[str]):
    args = _make_cli_args(format="css")
    rc = cmd_adopt(args)
    assert rc == 2
    err = capsys.readouterr().err
    assert "--format less only" in err


def test_cmd_adopt_without_target_or_device_errors(capsys):
    args = _make_cli_args(from_device=None, target=None)
    rc = cmd_adopt(args)
    assert rc == 2
    assert "target directory or --from-device" in capsys.readouterr().err


def test_cmd_adopt_refuses_to_overwrite(tmp_path: Path, monkeypatch,
                                        capsys: pytest.CaptureFixture[str]):
    out = tmp_path / "app.doql.less"
    out.write_text("// pre-existing", encoding="utf-8")

    args = _make_cli_args(output=str(out), force=False)
    rc = cmd_adopt(args)

    assert rc == 1
    assert "already exists" in capsys.readouterr().out
