"""Docker Compose / Dockerfile generator."""
from __future__ import annotations

import pathlib
import textwrap

from ...parser import DoqlSpec
from ...utils.naming import slug


def _gen_docker_compose(spec: DoqlSpec, env_vars: dict[str, str], out: pathlib.Path) -> None:
    slug_name = slug(spec.app_name)
    domain = spec.domain or env_vars.get("DOMAIN", f"{slug_name}.localhost")
    le_email = env_vars.get("LE_EMAIL", "ops@example.com")
    has_traefik = any(
        i.name == "web" or i.name == "api" for i in spec.interfaces
    )

    lines = [
        f"# Generated by doql build for {spec.app_name}",
        "services:",
        "",
        "  api:",
        f"    build:",
        f"      context: ../api",
        f"      dockerfile: ../infra/Dockerfile",
        f"    container_name: {slug_name}-api",
        f"    restart: unless-stopped",
        f"    env_file: .env.docker",
        f"    ports:",
        f"      - '8000:8000'",
        f"    volumes:",
        f"      - data:/app/data",
    ]
    if has_traefik:
        lines += [
            f"    labels:",
            f'      - "traefik.enable=true"',
            f'      - "traefik.http.routers.{slug_name}.rule=Host(`{domain}`)"',
            f'      - "traefik.http.routers.{slug_name}.tls.certresolver=letsencrypt"',
            f'      - "traefik.http.services.{slug_name}.loadbalancer.server.port=8000"',
        ]

    if has_traefik:
        lines += [
            "",
            "  traefik:",
            "    image: traefik:v3",
            "    container_name: traefik",
            "    restart: unless-stopped",
            "    command:",
            "      - --api.insecure=true",
            "      - --providers.docker=true",
            "      - --providers.docker.exposedbydefault=false",
            "      - --entrypoints.web.address=:80",
            "      - --entrypoints.websecure.address=:443",
            "      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web",
            f"      - --certificatesresolvers.letsencrypt.acme.email={le_email}",
            "      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json",
            "    ports:",
            "      - '80:80'",
            "      - '443:443'",
            "    volumes:",
            "      - /var/run/docker.sock:/var/run/docker.sock:ro",
            "      - letsencrypt:/letsencrypt",
        ]

    lines += [
        "",
        "volumes:",
        "  data:",
    ]
    if has_traefik:
        lines.append("  letsencrypt:")
    lines.append("")

    (out / "docker-compose.yml").write_text("\n".join(lines), encoding="utf-8")
    print(f"    → infra/docker-compose.yml")

    # Dockerfile
    dockerfile = textwrap.dedent(f"""\
        # Generated by doql build
        FROM python:3.13-slim AS base
        WORKDIR /app
        COPY requirements.txt .
        RUN pip install --no-cache-dir -r requirements.txt
        COPY . .
        EXPOSE 8000
        CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    """)
    (out / "Dockerfile").write_text(dockerfile, encoding="utf-8")
    print(f"    → infra/Dockerfile")

    # .env.docker
    env_lines = [f"# Environment for {spec.app_name} (docker-compose)"]
    env_lines.append(f"APP_NAME={spec.app_name}")
    env_lines.append(f"DATABASE_URL=sqlite:///./data/app.db")
    for ref in spec.env_refs:
        val = env_vars.get(ref, "")
        env_lines.append(f"{ref}={val}")
    env_lines.append("")
    (out / ".env.docker").write_text("\n".join(env_lines), encoding="utf-8")
    print(f"    → infra/.env.docker")
