"""Kiosk appliance generator."""
from __future__ import annotations

import pathlib
import textwrap

from ...parser import DoqlSpec
from ...utils.naming import slug


def _gen_kiosk(spec: DoqlSpec, env_vars: dict[str, str], out: pathlib.Path) -> None:
    slug_name = slug(spec.app_name)
    app_url = env_vars.get("KIOSK_URL", "http://localhost:8000")

    script = textwrap.dedent(f"""\
        #!/usr/bin/env bash
        # Generated by doql build — Kiosk appliance installer
        # Target: Raspberry Pi OS Lite 64-bit / any Debian-based
        set -euo pipefail

        APP_NAME="{spec.app_name}"
        KIOSK_URL="{app_url}"
        KIOSK_USER="kiosk"

        echo "🖥  Installing $APP_NAME kiosk..."

        # 1. System packages
        sudo apt-get update -qq
        sudo apt-get install -y -qq \\
            xserver-xorg xinit openbox \\
            chromium-browser \\
            unclutter \\
            lightdm \\
            pulseaudio

        # 2. Create kiosk user
        if ! id "$KIOSK_USER" &>/dev/null; then
            sudo useradd -m -s /bin/bash "$KIOSK_USER"
        fi

        # 3. Openbox autostart → Chromium kiosk
        sudo mkdir -p /home/$KIOSK_USER/.config/openbox
        cat <<'AUTOSTART' | sudo tee /home/$KIOSK_USER/.config/openbox/autostart
        # Hide cursor after 5s idle
        unclutter -idle 5 -root &

        # Disable screen blanking
        xset s off
        xset -dpms
        xset s noblank

        # Start Chromium in kiosk mode
        chromium-browser \\
            --noerrdialogs \\
            --disable-infobars \\
            --kiosk \\
            --disable-translate \\
            --disable-features=TranslateUI \\
            --overscroll-history-navigation=0 \\
            "$KIOSK_URL"
        AUTOSTART
        sudo chown -R $KIOSK_USER:$KIOSK_USER /home/$KIOSK_USER/.config

        # 4. LightDM autologin
        sudo mkdir -p /etc/lightdm/lightdm.conf.d
        cat <<EOF | sudo tee /etc/lightdm/lightdm.conf.d/50-kiosk.conf
        [Seat:*]
        autologin-user=$KIOSK_USER
        autologin-session=openbox
        EOF

        # 5. Systemd service for the API backend
        sudo cp "$(dirname "$0")/kiosk.service" /etc/systemd/system/{slug_name}.service
        sudo systemctl daemon-reload
        sudo systemctl enable {slug_name}.service

        echo "✅ Kiosk installed. Reboot to start."
    """)
    (out / "install-kiosk.sh").write_text(script, encoding="utf-8")
    print(f"    → infra/install-kiosk.sh")

    # systemd service
    service = textwrap.dedent(f"""\
        # Generated by doql build
        [Unit]
        Description={spec.app_name} backend
        After=network-online.target

        [Service]
        Type=simple
        User=kiosk
        WorkingDirectory=/opt/{slug_name}
        ExecStart=/opt/{slug_name}/venv/bin/uvicorn main:app --host 0.0.0.0 --port 8000
        Restart=always
        RestartSec=5

        [Install]
        WantedBy=multi-user.target
    """)
    (out / "kiosk.service").write_text(service, encoding="utf-8")
    print(f"    → infra/kiosk.service")
