"""Kubernetes manifest generator."""
from __future__ import annotations

import pathlib
import textwrap

from ...parser import DoqlSpec
from ...utils.naming import slug


def _gen_kubernetes(spec: DoqlSpec, env_vars: dict[str, str], out: pathlib.Path) -> None:
    slug_name = slug(spec.app_name)
    domain = spec.domain or env_vars.get("DOMAIN", f"{slug_name}.localhost")
    replicas = 1
    for infra in spec.infrastructures:
        if infra.type in ("kubernetes", "k8s", "k3s"):
            replicas = infra.replicas or 1
            break

    deployment = textwrap.dedent(f"""\
        # Generated by doql build — Kubernetes manifest
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: {slug_name}
          labels:
            app: {slug_name}
        spec:
          replicas: {replicas}
          selector:
            matchLabels:
              app: {slug_name}
          template:
            metadata:
              labels:
                app: {slug_name}
            spec:
              containers:
                - name: api
                  image: "{slug_name}:latest"
                  ports:
                    - containerPort: 8000
                  envFrom:
                    - configMapRef:
                        name: {slug_name}-config
                  volumeMounts:
                    - name: data
                      mountPath: /app/data
              volumes:
                - name: data
                  emptyDir: {{}}
    """)
    (out / "deployment.yaml").write_text(deployment, encoding="utf-8")
    print(f"    → infra/deployment.yaml")

    service = textwrap.dedent(f"""\
        apiVersion: v1
        kind: Service
        metadata:
          name: {slug_name}
        spec:
          selector:
            app: {slug_name}
          ports:
            - port: 8000
              targetPort: 8000
    """)
    (out / "service.yaml").write_text(service, encoding="utf-8")
    print(f"    → infra/service.yaml")

    config = textwrap.dedent(f"""\
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: {slug_name}-config
        data:
          APP_NAME: "{spec.app_name}"
          DATABASE_URL: "sqlite:///./data/app.db"
    """)
    for ref in spec.env_refs:
        val = env_vars.get(ref, "")
        config = config.rstrip() + f'\n  {ref}: "{val}"\n'
    (out / "configmap.yaml").write_text(config, encoding="utf-8")
    print(f"    → infra/configmap.yaml")

    ingress = textwrap.dedent(f"""\
        apiVersion: networking.k8s.io/v1
        kind: Ingress
        metadata:
          name: {slug_name}
          annotations:
            traefik.ingress.kubernetes.io/router.tls: "true"
        spec:
          rules:
            - host: {domain}
              http:
                paths:
                  - path: /
                    pathType: Prefix
                    backend:
                      service:
                        name: {slug_name}
                        port:
                          number: 8000
    """)
    (out / "ingress.yaml").write_text(ingress, encoding="utf-8")
    print(f"    → infra/ingress.yaml")

    kustomize = textwrap.dedent("""\
        apiVersion: kustomize.config.k8s.io/v1beta1
        kind: Kustomization
        resources:
          - deployment.yaml
          - service.yaml
          - configmap.yaml
          - ingress.yaml
    """)
    (out / "kustomization.yaml").write_text(kustomize, encoding="utf-8")
    print(f"    → infra/kustomization.yaml")
