"""Redeploy migration spec generator."""
from __future__ import annotations

import pathlib

import yaml as _yaml

from ...parser import DoqlSpec
from ...utils.naming import slug


def _gen_migration_spec(spec: DoqlSpec, env_vars: dict[str, str], out: pathlib.Path) -> None:
    """Generate redeploy migration.yaml alongside docker-compose/quadlet artifacts.

    Allows ``redeploy run`` (no args) to deploy what ``doql build`` generated.
    Requires: pip install doql[deploy]  (installs redeploy>=0.1.2)
    """
    slug_name = slug(spec.app_name)
    domain = spec.domain or env_vars.get("DOMAIN", f"{slug_name}.example.com")
    host = env_vars.get("DEPLOY_HOST", "local")
    version = spec.version or "0.1.0"

    from ..infra_gen import _map_deploy_strategy
    target_strategy = _map_deploy_strategy(spec.deploy.target)
    verify_url = (
        env_vars.get("VERIFY_URL")
        or (f"https://{domain}/api/health" if host != "local" else f"http://localhost:8000/api/health")
    )

    migration: dict = {
        "name": slug_name,
        "description": f"Deploy {spec.app_name} — generated by doql build",
        "source": {
            "strategy": "docker_full",
            "host": "local",
            "app": slug_name,
            "version": version,
        },
        "target": {
            "strategy": target_strategy,
            "host": host,
            "app": slug_name,
            "version": version,
            "domain": domain,
            "remote_dir": env_vars.get("REMOTE_DIR", f"/opt/{slug_name}"),
            "env_file": ".env",
            "verify_url": verify_url,
            "verify_version": version[:3],
        },
        "notes": [
            f"Generated by doql build from {spec.app_name} DEPLOY: target: {spec.deploy.target}",
            f"Run: redeploy run --plan-only   (preview steps)",
            f"Run: redeploy run --dry-run     (dry run)",
            f"Run: redeploy run               (deploy!)",
            f"Set DEPLOY_HOST=user@VPS_IP before building to embed VPS address.",
        ],
    }

    # For kiosk: point to the install script generated by _gen_kiosk
    if spec.deploy.target == "kiosk-appliance":
        migration["extra_steps"] = [
            {
                "id": "run_kiosk_installer",
                "action": "ssh_cmd",
                "description": "Run doql-generated kiosk install script",
                "command": f"bash /opt/{slug_name}/infra/install-kiosk.sh",
                "risk": "medium",
            }
        ]

    dest = out / "migration.yaml"
    dest.write_text(_yaml.dump(migration, allow_unicode=True, sort_keys=False), encoding="utf-8")
    print(f"    → infra/migration.yaml  (redeploy spec)")
