"""Nginx reverse proxy generator."""
from __future__ import annotations

import pathlib
import textwrap

from ...parser import DoqlSpec
from ...utils.naming import slug


def _gen_nginx(spec: DoqlSpec, env_vars: dict[str, str], out: pathlib.Path) -> None:
    slug_name = slug(spec.app_name)
    domain = spec.domain or env_vars.get("DOMAIN", f"{slug_name}.localhost")
    upstream = "localhost:8000"
    tls_block = ""
    for ing in spec.ingresses:
        if ing.tls:
            tls_block = textwrap.dedent(f"""\
                listen 443 ssl;
                ssl_certificate /etc/nginx/ssl/{slug_name}.crt;
                ssl_certificate_key /etc/nginx/ssl/{slug_name}.key;
            """)
            break

    conf = textwrap.dedent(f'''\
        # Generated by doql build — Nginx reverse proxy
        upstream {slug_name}_api {{
            server {upstream};
        }}

        server {{
            listen 80;
            server_name {domain};
            {tls_block}

            location / {{
                proxy_pass http://{slug_name}_api;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }}
        }}
    ''')
    (out / "nginx.conf").write_text(conf, encoding="utf-8")
    print(f"    → infra/nginx.conf")

    dockerfile_nginx = textwrap.dedent("""\
        FROM nginx:alpine
        COPY nginx.conf /etc/nginx/conf.d/default.conf
        EXPOSE 80 443
    """)
    (out / "Dockerfile.nginx").write_text(dockerfile_nginx, encoding="utf-8")
    print(f"    → infra/Dockerfile.nginx")
