"""Podman Quadlet generator."""
from __future__ import annotations

import pathlib
import textwrap

from ...parser import DoqlSpec
from ...utils.naming import slug


def _gen_quadlet(spec: DoqlSpec, env_vars: dict[str, str], out: pathlib.Path) -> None:
    slug_name = slug(spec.app_name)
    domain = spec.domain or env_vars.get("DOMAIN", f"{slug_name}.localhost")
    le_email = env_vars.get("LE_EMAIL", "ops@example.com")
    rootless = spec.deploy.rootless

    # Main app container
    container = textwrap.dedent(f"""\
        # Generated by doql build — Podman Quadlet
        [Unit]
        Description={spec.app_name} API
        After=network-online.target

        [Container]
        Image=localhost/{slug_name}:latest
        PublishPort=8000:8000
        EnvironmentFile=%h/.config/containers/{slug_name}.env
        Volume={slug_name}-data:/app/data:Z
        {'Rootfs=true' if rootless else ''}

        [Service]
        Restart=always
        TimeoutStartSec=30

        [Install]
        WantedBy=default.target
    """)
    (out / f"{slug_name}.container").write_text(container, encoding="utf-8")
    print(f"    → infra/{slug_name}.container")

    # Traefik quadlet
    traefik = textwrap.dedent(f"""\
        # Generated by doql build — Traefik Quadlet
        [Unit]
        Description=Traefik reverse proxy for {spec.app_name}
        After=network-online.target

        [Container]
        Image=docker.io/library/traefik:v3
        PublishPort=80:80
        PublishPort=443:443
        Volume=/run/podman/podman.sock:/var/run/docker.sock:ro,z
        Volume={slug_name}-letsencrypt:/letsencrypt:Z
        Exec=--providers.docker=true \\
          --providers.docker.exposedbydefault=false \\
          --entrypoints.web.address=:80 \\
          --entrypoints.websecure.address=:443 \\
          --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web \\
          --certificatesresolvers.letsencrypt.acme.email={le_email} \\
          --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json

        [Service]
        Restart=always

        [Install]
        WantedBy=default.target
    """)
    (out / f"{slug_name}-traefik.container").write_text(traefik, encoding="utf-8")
    print(f"    → infra/{slug_name}-traefik.container")

    # .env file
    env_lines = [f"# Environment for {spec.app_name}"]
    env_lines.append(f"APP_NAME={spec.app_name}")
    env_lines.append(f"DOMAIN={domain}")
    env_lines.append(f"DATABASE_URL=sqlite:///./data/app.db")
    for ref in spec.env_refs:
        val = env_vars.get(ref, "")
        env_lines.append(f"{ref}={val}")
    env_lines.append("")
    (out / f"{slug_name}.env").write_text("\n".join(env_lines), encoding="utf-8")
    print(f"    → infra/{slug_name}.env")
