"""Terraform infrastructure generator."""
from __future__ import annotations

import pathlib
import textwrap

from ...parser import DoqlSpec
from ...utils.naming import slug


def _gen_terraform(spec: DoqlSpec, env_vars: dict[str, str], out: pathlib.Path) -> None:
    slug_name = slug(spec.app_name)
    main_tf = textwrap.dedent(f'''\
        # Generated by doql build — Terraform infrastructure
        terraform {{
          required_providers {{
            docker = {{
              source  = "kreuzwerker/docker"
              version = "~> 3.0"
            }}
          }}
        }}

        provider "docker" {{}}

        resource "docker_image" "{slug_name}" {{
          name = "{slug_name}:latest"
          keep_locally = true
        }}

        resource "docker_container" "{slug_name}" {{
          name  = "{slug_name}-api"
          image = docker_image.{slug_name}.name
          ports {{
            internal = 8000
            external = 8000
          }}
          env = [
            "APP_NAME={spec.app_name}",
          ]
        }}
    ''')
    (out / "main.tf").write_text(main_tf, encoding="utf-8")
    print(f"    → infra/main.tf")

    variables_tf = textwrap.dedent("""\
        variable "domain" {
          description = "Application domain"
          type        = string
          default     = "localhost"
        }

        variable "replicas" {
          description = "Number of replicas"
          type        = number
          default     = 1
        }
    """)
    (out / "variables.tf").write_text(variables_tf, encoding="utf-8")
    print(f"    → infra/variables.tf")

    outputs_tf = textwrap.dedent(f'''\
        output "container_name" {{
          value = docker_container.{slug_name}.name
        }}
    ''')
    (out / "outputs.tf").write_text(outputs_tf, encoding="utf-8")
    print(f"    → infra/outputs.tf")
