"""Generate FastAPI + SQLAlchemy backend from DoqlSpec."""
from __future__ import annotations

import io
import json
import pathlib
from typing import IO

from ..parser import DoqlSpec


def generate(spec: DoqlSpec, env_vars: dict[str, str], out: pathlib.Path) -> None:
    """Generate API layer files into *out* directory."""
    readme = out / "README.md"
    readme.write_text(
        f"# {spec.app_name} — API\n\n"
        f"Generated by `doql build`.\n\n"
        f"Entities: {', '.join(e.name for e in spec.entities)}\n",
        encoding="utf-8",
    )
    # TODO: Faza 1 — FastAPI routes, SQLAlchemy models, Alembic migrations
    print(f"    → {readme.relative_to(out.parent)} (stub)")


def export_openapi(spec: DoqlSpec, out: IO[str]) -> None:
    """Write OpenAPI 3.1 JSON to the given stream."""
    openapi = {
        "openapi": "3.1.0",
        "info": {"title": spec.app_name, "version": spec.version},
        "paths": {
            f"/api/v1/{e.name.lower()}s": {
                "get": {"summary": f"List {e.name}s", "responses": {"200": {"description": "OK"}}},
                "post": {"summary": f"Create {e.name}", "responses": {"201": {"description": "Created"}}},
            }
            for e in spec.entities
        },
    }
    json.dump(openapi, out, indent=2)
