"""Generate FastAPI + SQLAlchemy backend from DoqlSpec.

Produces:
  api/
  ├── main.py           — FastAPI app + CORS + lifespan
  ├── database.py       — SQLAlchemy engine + session
  ├── models.py         — ORM models from ENTITY
  ├── schemas.py        — Pydantic request/response schemas
  ├── routes.py         — CRUD endpoints for each ENTITY
  ├── requirements.txt  — pinned deps
  └── README.md
"""
from __future__ import annotations

import json
import pathlib
import textwrap
from typing import IO

from ..parser import DoqlSpec, Entity, EntityField


# ────────────────────────────────────────────────────────
# Type mapping: doql type → (SQLAlchemy, Python/Pydantic)
# ────────────────────────────────────────────────────────

_TYPE_MAP: dict[str, tuple[str, str]] = {
    "uuid":     ("String(36)",  "str"),
    "string":   ("String(255)", "str"),
    "text":     ("Text",        "str"),
    "int":      ("Integer",     "int"),
    "float":    ("Float",       "float"),
    "bool":     ("Boolean",     "bool"),
    "date":     ("Date",        "date"),
    "datetime": ("DateTime",    "datetime"),
    "json":     ("JSON",        "dict"),
    "image":    ("String(512)", "str"),
    "pdf":      ("String(512)", "str"),
    "oql":      ("String(255)", "str"),
    "enum":     ("String(64)",  "str"),
}


def _sa_type(f: EntityField) -> str:
    return _TYPE_MAP.get(f.type, ("String(255)", "str"))[0]


def _py_type(f: EntityField) -> str:
    base = _TYPE_MAP.get(f.type, ("", "str"))[1]
    if f.ref:
        return "str"
    if not f.required and not f.auto:
        return f"Optional[{base}]"
    return base


def _py_default(f: EntityField) -> str:
    if f.auto:
        return " = None"
    if f.default:
        val = f.default
        if f.type == "bool":
            return f" = {val.capitalize()}"
        if f.type == "int":
            return f" = {val}"
        return f' = "{val}"'
    if not f.required:
        return " = None"
    return ""


_PY_KEYWORDS = frozenset({
    "False", "None", "True", "and", "as", "assert", "async", "await",
    "break", "class", "continue", "def", "del", "elif", "else", "except",
    "finally", "for", "from", "global", "if", "import", "in", "is",
    "lambda", "nonlocal", "not", "or", "pass", "raise", "return",
    "try", "while", "with", "yield", "type",
})


def _safe_name(name: str) -> str:
    """Escape Python reserved keywords by appending underscore."""
    return f"{name}_" if name in _PY_KEYWORDS else name


def _snake(name: str) -> str:
    import re
    s1 = re.sub("(.)([A-Z][a-z]+)", r"\1_\2", name)
    return re.sub("([a-z0-9])([A-Z])", r"\1_\2", s1).lower()


# ────────────────────────────────────────────────────────
# File generators
# ────────────────────────────────────────────────────────

def _gen_database(spec: DoqlSpec, env_vars: dict[str, str]) -> str:
    db_url = env_vars.get("DATABASE_URL", "sqlite:///./data.db")
    return textwrap.dedent(f'''\
        """Database engine and session — generated by doql."""
        from sqlalchemy import create_engine
        from sqlalchemy.orm import sessionmaker, DeclarativeBase

        DATABASE_URL = "{db_url}"

        engine = create_engine(DATABASE_URL, connect_args={{"check_same_thread": False}} if "sqlite" in DATABASE_URL else {{}})
        SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)


        class Base(DeclarativeBase):
            pass


        def get_db():
            db = SessionLocal()
            try:
                yield db
            finally:
                db.close()
    ''')


def _gen_models(spec: DoqlSpec) -> str:
    lines = [
        '"""SQLAlchemy ORM models — generated by doql."""',
        "from sqlalchemy import Column, String, Integer, Float, Boolean, Text, Date, DateTime, JSON, ForeignKey",
        "from sqlalchemy.orm import relationship",
        "from database import Base",
        "",
    ]
    for ent in spec.entities:
        table = _snake(ent.name) + "s"
        lines.append(f"")
        lines.append(f"class {ent.name}(Base):")
        lines.append(f'    __tablename__ = "{table}"')
        lines.append(f"")
        for f in ent.fields:
            if f.computed:
                continue
            # Positional args first, then keyword args
            pos_args = [_sa_type(f)]
            if f.ref:
                fk_table = _snake(f.ref) + "s"
                pos_args.append(f'ForeignKey("{fk_table}.id")')
            kw_args: list[str] = []
            if f.name == "id":
                kw_args.append("primary_key=True")
            if f.unique:
                kw_args.append("unique=True")
            if not f.required and f.name != "id":
                kw_args.append("nullable=True")
            if f.default and f.type in ("int", "float", "bool"):
                val = f.default
                if f.type == "bool":
                    val = val.lower() in ("true", "1", "yes")
                kw_args.append(f"default={val}")
            all_args = pos_args + kw_args
            lines.append(f"    {_safe_name(f.name)} = Column({', '.join(all_args)})")
        lines.append("")
    return "\n".join(lines)


def _gen_schemas(spec: DoqlSpec) -> str:
    lines = [
        '"""Pydantic schemas — generated by doql."""',
        "from __future__ import annotations",
        "from datetime import date, datetime",
        "from typing import Optional",
        "from pydantic import BaseModel",
        "",
    ]
    for ent in spec.entities:
        # Create schema (no id, no auto)
        lines.append(f"")
        lines.append(f"class {ent.name}Create(BaseModel):")
        create_fields = [f for f in ent.fields if not f.auto and not f.computed]
        if not create_fields:
            lines.append("    pass")
        for f in create_fields:
            lines.append(f"    {_safe_name(f.name)}: {_py_type(f)}{_py_default(f)}")

        # Response schema (all fields)
        lines.append(f"")
        lines.append(f"class {ent.name}Response(BaseModel):")
        lines.append("    model_config = {'from_attributes': True}")
        resp_fields = [f for f in ent.fields if not f.computed]
        if not resp_fields:
            lines.append("    pass")
        for f in resp_fields:
            lines.append(f"    {_safe_name(f.name)}: {_py_type(f)}{' = None' if f.auto or not f.required else ''}")

        # Update schema (all optional)
        lines.append(f"")
        lines.append(f"class {ent.name}Update(BaseModel):")
        update_fields = [f for f in ent.fields if not f.auto and not f.computed and f.name != "id"]
        if not update_fields:
            lines.append("    pass")
        for f in update_fields:
            base_type = _TYPE_MAP.get(f.type, ("", "str"))[1]
            lines.append(f"    {_safe_name(f.name)}: Optional[{base_type}] = None")

        lines.append("")
    return "\n".join(lines)


def _gen_routes(spec: DoqlSpec) -> str:
    lines = [
        '"""CRUD routes — generated by doql."""',
        "from fastapi import APIRouter, Depends, HTTPException",
        "from sqlalchemy.orm import Session",
        "from database import get_db",
        "import models",
        "import schemas",
        "",
        "router = APIRouter(prefix='/api/v1')",
        "",
    ]
    for ent in spec.entities:
        name = ent.name
        lower = _snake(name)
        plural = lower + "s"

        lines.append(f"# ── {name} ──")
        lines.append(f"")

        # LIST
        lines.append(f'@router.get("/{plural}", response_model=list[schemas.{name}Response])')
        lines.append(f"def list_{plural}(skip: int = 0, limit: int = 100, db: Session = Depends(get_db)):")
        lines.append(f"    return db.query(models.{name}).offset(skip).limit(limit).all()")
        lines.append(f"")

        # GET
        lines.append(f'@router.get("/{plural}/{{item_id}}", response_model=schemas.{name}Response)')
        lines.append(f"def get_{lower}(item_id: str, db: Session = Depends(get_db)):")
        lines.append(f"    obj = db.query(models.{name}).filter(models.{name}.id == item_id).first()")
        lines.append(f"    if not obj:")
        lines.append(f'        raise HTTPException(404, "{name} not found")')
        lines.append(f"    return obj")
        lines.append(f"")

        # CREATE
        lines.append(f'@router.post("/{plural}", response_model=schemas.{name}Response, status_code=201)')
        lines.append(f"def create_{lower}(data: schemas.{name}Create, db: Session = Depends(get_db)):")
        lines.append(f"    obj = models.{name}(**data.model_dump())")
        lines.append(f"    db.add(obj)")
        lines.append(f"    db.commit()")
        lines.append(f"    db.refresh(obj)")
        lines.append(f"    return obj")
        lines.append(f"")

        # UPDATE
        lines.append(f'@router.patch("/{plural}/{{item_id}}", response_model=schemas.{name}Response)')
        lines.append(f"def update_{lower}(item_id: str, data: schemas.{name}Update, db: Session = Depends(get_db)):")
        lines.append(f"    obj = db.query(models.{name}).filter(models.{name}.id == item_id).first()")
        lines.append(f"    if not obj:")
        lines.append(f'        raise HTTPException(404, "{name} not found")')
        lines.append(f"    for key, val in data.model_dump(exclude_unset=True).items():")
        lines.append(f"        setattr(obj, key, val)")
        lines.append(f"    db.commit()")
        lines.append(f"    db.refresh(obj)")
        lines.append(f"    return obj")
        lines.append(f"")

        # DELETE
        lines.append(f'@router.delete("/{plural}/{{item_id}}", status_code=204)')
        lines.append(f"def delete_{lower}(item_id: str, db: Session = Depends(get_db)):")
        lines.append(f"    obj = db.query(models.{name}).filter(models.{name}.id == item_id).first()")
        lines.append(f"    if not obj:")
        lines.append(f'        raise HTTPException(404, "{name} not found")')
        lines.append(f"    db.delete(obj)")
        lines.append(f"    db.commit()")
        lines.append(f"")

    return "\n".join(lines)


def _gen_main(spec: DoqlSpec) -> str:
    return textwrap.dedent(f'''\
        """FastAPI application — generated by doql."""
        from contextlib import asynccontextmanager
        from fastapi import FastAPI
        from fastapi.middleware.cors import CORSMiddleware
        from database import engine, Base
        from routes import router

        @asynccontextmanager
        async def lifespan(app: FastAPI):
            Base.metadata.create_all(bind=engine)
            yield

        app = FastAPI(
            title="{spec.app_name}",
            version="{spec.version}",
            lifespan=lifespan,
        )

        app.add_middleware(
            CORSMiddleware,
            allow_origins=["*"],
            allow_credentials=True,
            allow_methods=["*"],
            allow_headers=["*"],
        )

        app.include_router(router)

        try:
            from auth import router as auth_router, User as AuthUser  # noqa: F401
            app.include_router(auth_router)
        except ImportError:
            pass


        @app.get("/health")
        def health():
            return {{"status": "ok", "app": "{spec.app_name}", "version": "{spec.version}"}}
    ''')


def _gen_auth(spec: DoqlSpec) -> str:
    roles = spec.roles if spec.roles else []
    roles_enum = ", ".join(f'"{r}"' for r in roles) if roles else '"admin", "user"'
    return textwrap.dedent(f'''\
        """JWT authentication — generated by doql."""
        import os
        from datetime import datetime, timedelta, timezone
        from typing import Optional

        from fastapi import APIRouter, Depends, HTTPException, status
        from fastapi.security import OAuth2PasswordBearer, OAuth2PasswordRequestForm
        from pydantic import BaseModel
        from sqlalchemy import Column, String, DateTime
        from sqlalchemy.orm import Session
        from jose import JWTError, jwt
        from passlib.context import CryptContext

        from database import Base, get_db

        SECRET_KEY = os.getenv("JWT_SECRET", "change-me-in-production")
        ALGORITHM = "HS256"
        ACCESS_TOKEN_EXPIRE_MINUTES = 60 * 8  # 8 hours

        ROLES = [{roles_enum}]

        pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")
        oauth2_scheme = OAuth2PasswordBearer(tokenUrl="/auth/login")
        router = APIRouter(prefix="/auth", tags=["auth"])


        class User(Base):
            __tablename__ = "users"
            id = Column(String(36), primary_key=True)
            username = Column(String(255), unique=True, nullable=False)
            email = Column(String(255), unique=True, nullable=True)
            hashed_password = Column(String(255), nullable=False)
            role = Column(String(64), default="user")
            created_at = Column(DateTime, default=datetime.now)


        class Token(BaseModel):
            access_token: str
            token_type: str = "bearer"


        class UserCreate(BaseModel):
            username: str
            password: str
            email: Optional[str] = None
            role: str = "user"


        class UserResponse(BaseModel):
            model_config = {{"from_attributes": True}}
            id: str
            username: str
            email: Optional[str] = None
            role: str


        def create_access_token(data: dict, expires_delta: timedelta | None = None) -> str:
            to_encode = data.copy()
            expire = datetime.now(timezone.utc) + (expires_delta or timedelta(minutes=ACCESS_TOKEN_EXPIRE_MINUTES))
            to_encode.update({{"exp": expire}})
            return jwt.encode(to_encode, SECRET_KEY, algorithm=ALGORITHM)


        def get_current_user(token: str = Depends(oauth2_scheme), db: Session = Depends(get_db)) -> User:
            credentials_exception = HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail="Invalid authentication credentials",
                headers={{"WWW-Authenticate": "Bearer"}},
            )
            try:
                payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
                user_id: str = payload.get("sub")
                if user_id is None:
                    raise credentials_exception
            except JWTError:
                raise credentials_exception
            user = db.query(User).filter(User.id == user_id).first()
            if user is None:
                raise credentials_exception
            return user


        def require_role(*allowed_roles: str):
            def checker(current_user: User = Depends(get_current_user)):
                if current_user.role not in allowed_roles:
                    raise HTTPException(status_code=403, detail="Insufficient permissions")
                return current_user
            return checker


        @router.post("/register", response_model=UserResponse, status_code=201)
        def register(data: UserCreate, db: Session = Depends(get_db)):
            import uuid
            existing = db.query(User).filter(User.username == data.username).first()
            if existing:
                raise HTTPException(400, "Username already taken")
            user = User(
                id=str(uuid.uuid4()),
                username=data.username,
                email=data.email,
                hashed_password=pwd_context.hash(data.password),
                role=data.role if data.role in ROLES else "user",
            )
            db.add(user)
            db.commit()
            db.refresh(user)
            return user


        @router.post("/login", response_model=Token)
        def login(form: OAuth2PasswordRequestForm = Depends(), db: Session = Depends(get_db)):
            user = db.query(User).filter(User.username == form.username).first()
            if not user or not pwd_context.verify(form.password, user.hashed_password):
                raise HTTPException(401, "Incorrect username or password")
            token = create_access_token({{"sub": user.id, "role": user.role}})
            return {{"access_token": token}}


        @router.get("/me", response_model=UserResponse)
        def me(current_user: User = Depends(get_current_user)):
            return current_user
    ''')


def _gen_alembic_ini() -> str:
    return textwrap.dedent("""\
        # Alembic config — generated by doql
        [alembic]
        script_location = alembic
        sqlalchemy.url = sqlite:///./data.db

        [loggers]
        keys = root,sqlalchemy,alembic

        [handlers]
        keys = console

        [formatters]
        keys = generic

        [logger_root]
        level = WARN
        handlers = console

        [logger_sqlalchemy]
        level = WARN
        handlers =
        qualname = sqlalchemy.engine

        [logger_alembic]
        level = INFO
        handlers =
        qualname = alembic

        [handler_console]
        class = StreamHandler
        args = (sys.stderr,)
        level = NOTSET
        formatter = generic

        [formatter_generic]
        format = %(levelname)-5.5s [%(name)s] %(message)s
    """)


def _gen_alembic_env() -> str:
    return (
        '# Alembic env.py — generated by doql\n'
        'from logging.config import fileConfig\n'
        'from alembic import context\n'
        'from sqlalchemy import engine_from_config, pool\n'
        'import sys, os\n'
        '\n'
        'sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))\n'
        'from database import Base\n'
        'import models  # noqa: F401\n'
        '\n'
        'config = context.config\n'
        'if config.config_file_name:\n'
        '    fileConfig(config.config_file_name)\n'
        '\n'
        'target_metadata = Base.metadata\n'
        '\n'
        '\n'
        'def run_migrations_offline():\n'
        '    url = config.get_main_option("sqlalchemy.url")\n'
        '    context.configure(url=url, target_metadata=target_metadata, literal_binds=True)\n'
        '    with context.begin_transaction():\n'
        '        context.run_migrations()\n'
        '\n'
        '\n'
        'def run_migrations_online():\n'
        '    connectable = engine_from_config(\n'
        '        config.get_section(config.config_ini_section),\n'
        '        prefix="sqlalchemy.",\n'
        '        poolclass=pool.NullPool,\n'
        '    )\n'
        '    with connectable.connect() as connection:\n'
        '        context.configure(connection=connection, target_metadata=target_metadata)\n'
        '        with context.begin_transaction():\n'
        '            context.run_migrations()\n'
        '\n'
        '\n'
        'if context.is_offline_mode():\n'
        '    run_migrations_offline()\n'
        'else:\n'
        '    run_migrations_online()\n'
    )


def _gen_initial_migration(spec: DoqlSpec) -> str:
    """Generate initial Alembic migration with all tables."""
    lines = [
        '"""Initial migration — generated by doql."""',
        'revision = "001"',
        'down_revision = None',
        '',
        'from alembic import op',
        'import sqlalchemy as sa',
        '',
        '',
        'def upgrade():',
    ]
    for ent in spec.entities:
        table = _snake(ent.name) + "s"
        lines.append(f'    op.create_table(')
        lines.append(f'        "{table}",')
        for f in ent.fields:
            if f.computed:
                continue
            sa_type = _sa_type(f)
            col_args = []
            if f.name == "id":
                col_args.append("primary_key=True")
            if f.unique:
                col_args.append("unique=True")
            if not f.required and f.name != "id":
                col_args.append("nullable=True")
            args_str = ", ".join(col_args)
            if args_str:
                lines.append(f'        sa.Column("{_safe_name(f.name)}", sa.{sa_type}, {args_str}),')
            else:
                lines.append(f'        sa.Column("{_safe_name(f.name)}", sa.{sa_type}),')
        lines.append(f'    )')
    lines.append('')
    lines.append('')
    lines.append('def downgrade():')
    for ent in reversed(spec.entities):
        table = _snake(ent.name) + "s"
        lines.append(f'    op.drop_table("{table}")')
    lines.append('')
    return "\n".join(lines)


def _gen_requirements(has_auth: bool = False) -> str:
    lines = [
        "fastapi>=0.104",
        "uvicorn[standard]>=0.24",
        "sqlalchemy>=2.0",
        "alembic>=1.13",
        "pydantic>=2.0",
        "python-dotenv>=1.0",
    ]
    if has_auth:
        lines += [
            "python-jose[cryptography]>=3.3",
            "passlib[bcrypt]>=1.7",
            "python-multipart>=0.0.6",
        ]
    return "\n".join(lines) + "\n"


# ────────────────────────────────────────────────────────
# Public API
# ────────────────────────────────────────────────────────

def generate(spec: DoqlSpec, env_vars: dict[str, str], out: pathlib.Path) -> None:
    """Generate API layer files into *out* directory."""
    if not spec.entities:
        readme = out / "README.md"
        readme.write_text(
            f"# {spec.app_name} — API\n\nNo entities defined — skipping code generation.\n",
            encoding="utf-8",
        )
        print(f"    → api/ (no entities, skipped)")
        return

    has_auth = bool(spec.roles)
    files = {
        "main.py":          _gen_main(spec),
        "database.py":      _gen_database(spec, env_vars),
        "models.py":        _gen_models(spec),
        "schemas.py":       _gen_schemas(spec),
        "routes.py":        _gen_routes(spec),
        "requirements.txt": _gen_requirements(has_auth=has_auth),
    }
    if has_auth:
        files["auth.py"] = _gen_auth(spec)
    for name, content in files.items():
        (out / name).write_text(content, encoding="utf-8")
        print(f"    → api/{name}")

    # Alembic migrations
    alembic_dir = out / "alembic" / "versions"
    alembic_dir.mkdir(parents=True, exist_ok=True)
    (out / "alembic.ini").write_text(_gen_alembic_ini(), encoding="utf-8")
    (out / "alembic" / "env.py").write_text(_gen_alembic_env(), encoding="utf-8")
    (alembic_dir / "001_initial.py").write_text(_gen_initial_migration(spec), encoding="utf-8")
    print(f"    → api/alembic.ini, alembic/env.py, alembic/versions/001_initial.py")

    readme = out / "README.md"
    readme.write_text(
        f"# {spec.app_name} — API\n\n"
        f"Generated by `doql build`.\n\n"
        f"## Quick start\n\n"
        f"```bash\n"
        f"cd build/api\n"
        f"pip install -r requirements.txt\n"
        f"uvicorn main:app --reload\n"
        f"```\n\n"
        f"## Entities\n\n"
        + "\n".join(f"- **{e.name}** ({len(e.fields)} fields)" for e in spec.entities)
        + "\n\n"
        f"## Endpoints\n\n"
        + "\n".join(
            f"- `GET /api/v1/{_snake(e.name)}s` · `POST` · `GET /:id` · `PATCH /:id` · `DELETE /:id`"
            for e in spec.entities
        )
        + "\n",
        encoding="utf-8",
    )
    print(f"    → api/README.md")


def export_openapi(spec: DoqlSpec, out: IO[str]) -> None:
    """Write OpenAPI 3.1 JSON to the given stream."""
    paths = {}
    for e in spec.entities:
        plural = _snake(e.name) + "s"
        base = f"/api/v1/{plural}"
        paths[base] = {
            "get": {
                "summary": f"List {e.name}s",
                "responses": {"200": {"description": "OK"}},
            },
            "post": {
                "summary": f"Create {e.name}",
                "responses": {"201": {"description": "Created"}},
            },
        }
        paths[f"{base}/{{id}}"] = {
            "get":    {"summary": f"Get {e.name}", "responses": {"200": {"description": "OK"}}},
            "patch":  {"summary": f"Update {e.name}", "responses": {"200": {"description": "OK"}}},
            "delete": {"summary": f"Delete {e.name}", "responses": {"204": {"description": "No Content"}}},
        }
    openapi = {
        "openapi": "3.1.0",
        "info": {"title": spec.app_name, "version": spec.version},
        "paths": paths,
    }
    json.dump(openapi, out, indent=2)
