"""Generate CI/CD configuration files.

Produces:
  .github/workflows/doql-ci.yml  — GitHub Actions workflow for validate + build + test
"""
from __future__ import annotations

import pathlib
import textwrap

from ..parser import DoqlSpec


def _gen_github_action(spec: DoqlSpec) -> str:
    """Generate a GitHub Actions workflow for doql projects."""
    return textwrap.dedent(f'''\
        name: doql CI

        on:
          push:
            branches: [main, develop]
          pull_request:
            branches: [main]

        jobs:
          validate:
            runs-on: ubuntu-latest
            steps:
              - uses: actions/checkout@v4
              - uses: actions/setup-python@v5
                with:
                  python-version: "3.12"
              - name: Install doql
                run: pip install doql
              - name: Validate
                run: doql validate
              - name: Build
                run: doql build --force
              - name: Check generated Python
                run: |
                  cd build/api
                  python -c "
                  import py_compile, os
                  for r, d, fs in os.walk('.'):
                      for f in fs:
                          if f.endswith('.py'):
                              py_compile.compile(os.path.join(r,f), doraise=True)
                  print('All Python files compile OK')
                  "

          api-test:
            runs-on: ubuntu-latest
            needs: validate
            steps:
              - uses: actions/checkout@v4
              - uses: actions/setup-python@v5
                with:
                  python-version: "3.12"
              - name: Install doql & build
                run: |
                  pip install doql
                  doql build --force
              - name: Install API deps
                run: |
                  cd build/api
                  pip install -r requirements.txt
              - name: API smoke test
                run: |
                  cd build/api
                  timeout 10 python -c "
                  from main import app
                  from fastapi.testclient import TestClient
                  client = TestClient(app)
                  r = client.get('/health')
                  assert r.status_code == 200
                  assert r.json()['status'] == 'ok'
                  print('Health check passed')
                  " || true

          web-build:
            runs-on: ubuntu-latest
            needs: validate
            steps:
              - uses: actions/checkout@v4
              - uses: actions/setup-node@v4
                with:
                  node-version: "20"
              - uses: actions/setup-python@v5
                with:
                  python-version: "3.12"
              - name: Install doql & build
                run: |
                  pip install doql
                  doql build --force
              - name: Install web deps
                run: |
                  cd build/web
                  npm install
              - name: Build web
                run: |
                  cd build/web
                  npm run build
    ''')


def _gen_gitlab_ci(spec: DoqlSpec) -> str:
    """Generate a GitLab CI/CD pipeline (.gitlab-ci.yml)."""
    slug = spec.app_name.lower().replace(" ", "-").replace("_", "-")
    stages = ["validate", "build", "test", "deploy"]
    return textwrap.dedent(f'''\
        # Generated by doql build — GitLab CI
        image: python:3.12-slim

        stages:
          - validate
          - build
          - test
          - deploy

        variables:
          PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

        validate:
          stage: validate
          script:
            - pip install doql
            - doql validate
          only:
            - main
            - develop
            - merge_requests

        build:
          stage: build
          needs: [validate]
          script:
            - pip install doql
            - doql build --force
          artifacts:
            paths:
              - build/
            expire_in: 1 hour

        api-test:
          stage: test
          needs: [build]
          image: python:3.12-slim
          script:
            - cd build/api
            - pip install -r requirements.txt || true
            - python -c "from main import app; print('API import OK')"

        web-build:
          stage: test
          needs: [build]
          image: node:20-slim
          script:
            - cd build/web
            - npm install || true
            - npm run build || true

        deploy:
          stage: deploy
          needs: [api-test, web-build]
          script:
            - echo "Deploy {slug}"
          when: manual
    ''')


def _gen_jenkinsfile(spec: DoqlSpec) -> str:
    """Generate a Jenkins declarative pipeline (Jenkinsfile)."""
    return textwrap.dedent(f'''\
        // Generated by doql build — Jenkins pipeline
        pipeline {{
            agent any
            stages {{
                stage('Validate') {{
                    steps {{
                        sh 'pip install doql && doql validate'
                    }}
                }}
                stage('Build') {{
                    steps {{
                        sh 'pip install doql && doql build --force'
                    }}
                }}
                stage('API Smoke Test') {{
                    steps {{
                        dir('build/api') {{
                            sh 'pip install -r requirements.txt || true'
                            sh 'python -c "from main import app; print(\\'API import OK\\')"'
                        }}
                    }}
                }}
                stage('Web Build') {{
                    agent {{ label 'nodejs' }}
                    steps {{
                        dir('build/web') {{
                            sh 'npm install || true'
                            sh 'npm run build || true'
                        }}
                    }}
                }}
            }}
            post {{
                always {{
                    cleanWs()
                }}
            }}
        }}
    ''')


def generate(spec: DoqlSpec, env_vars: dict[str, str], out: pathlib.Path) -> None:
    """Generate CI configuration files based on ci_configs or fallback to GitHub Actions."""
    ci_types = {c.type for c in spec.ci_configs}

    # Fallback to github if no CI blocks declared
    if not ci_types:
        ci_types = {"github"}

    for ctype in ci_types:
        if ctype in ("github", "github-actions"):
            gh_dir = out / ".github" / "workflows"
            gh_dir.mkdir(parents=True, exist_ok=True)
            (gh_dir / "doql-ci.yml").write_text(_gen_github_action(spec), encoding="utf-8")
            print(f"    → .github/workflows/doql-ci.yml")
        elif ctype in ("gitlab", "gitlab-ci"):
            (out / ".gitlab-ci.yml").write_text(_gen_gitlab_ci(spec), encoding="utf-8")
            print(f"    → .gitlab-ci.yml")
        elif ctype in ("jenkins",):
            (out / "Jenkinsfile").write_text(_gen_jenkinsfile(spec), encoding="utf-8")
            print(f"    → Jenkinsfile")
        else:
            # Unknown CI provider: default to GitHub Actions
            gh_dir = out / ".github" / "workflows"
            gh_dir.mkdir(parents=True, exist_ok=True)
            (gh_dir / "doql-ci.yml").write_text(_gen_github_action(spec), encoding="utf-8")
            print(f"    → .github/workflows/doql-ci.yml")
