"""Generate Tauri desktop shell from DoqlSpec.

Produces:
  build/desktop/
  ├── src-tauri/
  │   ├── Cargo.toml
  │   ├── tauri.conf.json
  │   ├── build.rs
  │   └── src/
  │       └── main.rs
  └── README.md

The Tauri shell wraps the web build from build/web/dist and adds:
  - native menu
  - system tray (optional)
  - auto-update stub
"""
from __future__ import annotations

import json
import pathlib
import re
import textwrap

from ..parser import DoqlSpec


def _snake(name: str) -> str:
    s1 = re.sub("(.)([A-Z][a-z]+)", r"\1_\2", name)
    return re.sub("([a-z0-9])([A-Z])", r"\1_\2", s1).lower().replace(" ", "_")


def _gen_cargo_toml(spec: DoqlSpec) -> str:
    pkg_name = _snake(spec.app_name)
    return textwrap.dedent(f'''\
        [package]
        name = "{pkg_name}"
        version = "{spec.version}"
        edition = "2021"

        [build-dependencies]
        tauri-build = {{ version = "1.5", features = [] }}

        [dependencies]
        tauri = {{ version = "1.5", features = ["shell-open", "system-tray"] }}
        serde = {{ version = "1", features = ["derive"] }}
        serde_json = "1"

        [features]
        default = ["custom-protocol"]
        custom-protocol = ["tauri/custom-protocol"]
    ''')


def _gen_tauri_conf(spec: DoqlSpec) -> str:
    identifier = f"com.doql.{_snake(spec.app_name)}"
    return json.dumps({
        "build": {
            "beforeBuildCommand": "cd ../../web && npm run build",
            "beforeDevCommand": "cd ../../web && npm run dev",
            "devPath": "http://localhost:5173",
            "distDir": "../../web/dist",
        },
        "package": {
            "productName": spec.app_name,
            "version": spec.version,
        },
        "tauri": {
            "allowlist": {
                "all": False,
                "shell": {"open": True},
            },
            "bundle": {
                "active": True,
                "identifier": identifier,
                "targets": "all",
                "icon": [
                    "icons/32x32.png",
                    "icons/128x128.png",
                    "icons/icon.icns",
                    "icons/icon.ico",
                ],
            },
            "security": {
                "csp": None,
            },
            "systemTray": {
                "iconPath": "icons/icon.png",
                "iconAsTemplate": True,
            },
            "updater": {
                "active": False,
                "endpoints": [],
            },
            "windows": [
                {
                    "title": spec.app_name,
                    "width": 1280,
                    "height": 800,
                    "resizable": True,
                    "fullscreen": False,
                }
            ],
        },
    }, indent=2)


def _gen_main_rs(spec: DoqlSpec) -> str:
    return textwrap.dedent('''\
        // Tauri main entry — generated by doql
        #![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

        use tauri::{CustomMenuItem, Menu, MenuItem, Submenu, SystemTray, SystemTrayEvent, SystemTrayMenu, SystemTrayMenuItem};

        fn main() {
            let quit = CustomMenuItem::new("quit".to_string(), "Quit");
            let hide = CustomMenuItem::new("hide".to_string(), "Hide");
            let tray_menu = SystemTrayMenu::new()
                .add_item(hide)
                .add_native_item(SystemTrayMenuItem::Separator)
                .add_item(quit);
            let system_tray = SystemTray::new().with_menu(tray_menu);

            let app_menu = Submenu::new("App", Menu::new()
                .add_native_item(MenuItem::About("About".to_string(), Default::default()))
                .add_native_item(MenuItem::Separator)
                .add_native_item(MenuItem::Quit));
            let menu = Menu::new().add_submenu(app_menu);

            tauri::Builder::default()
                .menu(menu)
                .system_tray(system_tray)
                .on_system_tray_event(|app, event| match event {
                    SystemTrayEvent::MenuItemClick { id, .. } => match id.as_str() {
                        "quit" => std::process::exit(0),
                        "hide" => {
                            if let Some(window) = app.get_window("main") {
                                let _ = window.hide();
                            }
                        }
                        _ => {}
                    },
                    _ => {}
                })
                .run(tauri::generate_context!())
                .expect("error while running tauri application");
        }
    ''')


def _gen_build_rs() -> str:
    return textwrap.dedent('''\
        fn main() {
            tauri_build::build()
        }
    ''')


def _gen_package_json(spec: DoqlSpec) -> str:
    pkg_name = _snake(spec.app_name)
    return json.dumps({
        "name": f"{pkg_name}-desktop",
        "version": spec.version,
        "private": True,
        "scripts": {
            "dev": "tauri dev",
            "build": "tauri build",
            "tauri": "tauri",
        },
        "devDependencies": {
            "@tauri-apps/cli": "^1.5.0",
        },
    }, indent=2)


def generate(spec: DoqlSpec, env_vars: dict[str, str], out: pathlib.Path) -> None:
    """Generate desktop (Tauri) layer files into *out* directory."""
    desktop_iface = next((i for i in spec.interfaces if i.type in ("electron", "tauri")), None)
    if not desktop_iface:
        (out / "README.md").write_text(
            f"# {spec.app_name} — Desktop\n\nNo desktop interface (type: tauri|electron) defined.\n",
            encoding="utf-8",
        )
        print(f"    → desktop/README.md (skipped, no desktop interface)")
        return

    src_tauri = out / "src-tauri"
    src_dir = src_tauri / "src"
    for d in (src_tauri, src_dir):
        d.mkdir(parents=True, exist_ok=True)

    (out / "package.json").write_text(_gen_package_json(spec), encoding="utf-8")
    (src_tauri / "Cargo.toml").write_text(_gen_cargo_toml(spec), encoding="utf-8")
    (src_tauri / "tauri.conf.json").write_text(_gen_tauri_conf(spec), encoding="utf-8")
    (src_tauri / "build.rs").write_text(_gen_build_rs(), encoding="utf-8")
    (src_dir / "main.rs").write_text(_gen_main_rs(spec), encoding="utf-8")

    print(f"    → desktop/package.json")
    print(f"    → desktop/src-tauri/Cargo.toml, tauri.conf.json, build.rs")
    print(f"    → desktop/src-tauri/src/main.rs")

    (out / "README.md").write_text(
        f"# {spec.app_name} — Desktop (Tauri)\n\n"
        f"Generated by `doql build`. Tauri 1.5 shell wrapping the web frontend.\n\n"
        f"## Prerequisites\n\n"
        f"- Rust toolchain: <https://rustup.rs>\n"
        f"- Node 20+ (for the web frontend)\n\n"
        f"## Quick start\n\n"
        f"```bash\ncd build/desktop\nnpm install\nnpm run dev\n```\n\n"
        f"## Build installer\n\n"
        f"```bash\nnpm run build\n# Artifacts in src-tauri/target/release/bundle/\n```\n",
        encoding="utf-8",
    )
    print(f"    → desktop/README.md")
