"""Generate Tauri desktop shell from DoqlSpec."""
from __future__ import annotations

import pathlib

from ..parser import DoqlSpec


def generate(spec: DoqlSpec, env_vars: dict[str, str], out: pathlib.Path) -> None:
    """Generate desktop layer files into *out* directory."""
    readme = out / "README.md"
    readme.write_text(
        f"# {spec.app_name} — Desktop (Tauri)\n\n"
        f"Generated by `doql build`.\n",
        encoding="utf-8",
    )
    # TODO: Faza 2 — Tauri config, system tray, auto-update
    print(f"    → {readme.relative_to(out.parent)} (stub)")
