"""Generate Tauri desktop shell from DoqlSpec.

Produces:
  build/desktop/
  ├── src-tauri/
  │   ├── Cargo.toml
  │   ├── tauri.conf.json
  │   ├── build.rs
  │   └── src/
  │       └── main.rs
  └── README.md

The Tauri shell wraps the web build from build/web/dist and adds:
  - native menu
  - system tray (optional)
  - auto-update stub
"""
from __future__ import annotations

import json
import pathlib
import re
import struct
import textwrap
import zlib

from ..parser import DoqlSpec


def _make_solid_png(width: int, height: int, rgb: tuple[int, int, int]) -> bytes:
    """Return a valid RGBA PNG of given size filled with one color (stdlib only).

    Tauri requires an RGBA window icon (color type 6) — RGB is rejected.
    """
    sig = b"\x89PNG\r\n\x1a\n"

    def chunk(tag: bytes, data: bytes) -> bytes:
        return struct.pack(">I", len(data)) + tag + data + struct.pack(">I", zlib.crc32(tag + data))

    # color type 6 = RGBA (truecolor + alpha)
    ihdr = chunk(b"IHDR", struct.pack(">IIBBBBB", width, height, 8, 6, 0, 0, 0))
    row = bytes([rgb[0], rgb[1], rgb[2], 0xFF]) * width
    raw = b"".join(b"\x00" + row for _ in range(height))
    idat = chunk(b"IDAT", zlib.compress(raw, 9))
    iend = chunk(b"IEND", b"")
    return sig + ihdr + idat + iend


def _snake(name: str) -> str:
    s1 = re.sub("(.)([A-Z][a-z]+)", r"\1_\2", name)
    return re.sub("([a-z0-9])([A-Z])", r"\1_\2", s1).lower().replace(" ", "_")


def _gen_cargo_toml(spec: DoqlSpec) -> str:
    pkg_name = _snake(spec.app_name)
    return textwrap.dedent(f'''\
        [package]
        name = "{pkg_name}"
        version = "{spec.version}"
        edition = "2021"

        [build-dependencies]
        tauri-build = {{ version = "2", features = [] }}

        [dependencies]
        tauri = {{ version = "2", features = [] }}
        serde = {{ version = "1", features = ["derive"] }}
        serde_json = "1"
    ''')


def _gen_tauri_conf(spec: DoqlSpec) -> str:
    """Tauri **v2** config schema.

    v2 uses webkit2gtk-4.1 + libsoup-3.0 which are available on Ubuntu 24.04+.
    The legacy v1 stack (webkit2gtk-4.0, libsoup-2.4) is no longer packaged
    on most modern distros.
    """
    identifier = f"com.doql.{_snake(spec.app_name)}"
    return json.dumps({
        "$schema": "https://schema.tauri.app/config/2",
        "productName": spec.app_name,
        "version": spec.version,
        "identifier": identifier,
        "build": {
            # beforeBuildCommand / beforeDevCommand are executed from the
            # tauri *project* directory (= build/desktop/), not from src-tauri/.
            "beforeBuildCommand": "cd ../web && npm install --silent && npm run build",
            "beforeDevCommand": "cd ../web && npm install --silent && npm run dev",
            "devUrl": "http://localhost:5173",
            # frontendDist is resolved relative to src-tauri/.
            "frontendDist": "../../web/dist",
        },
        "app": {
            "windows": [
                {
                    "title": spec.app_name,
                    "width": 1280,
                    "height": 800,
                    "resizable": True,
                    "fullscreen": False,
                }
            ],
            "security": {
                "csp": None,
            },
        },
        "bundle": {
            # Bundling disabled by default (release packaging needs proper icons).
            # `tauri dev` still requires *one* PNG referenced below.
            "active": False,
            "targets": "all",
            "icon": ["icons/icon.png"],
        },
    }, indent=2)


def _gen_main_rs(spec: DoqlSpec) -> str:
    """Tauri v2 main entry — minimal, no plugins required."""
    return textwrap.dedent('''\
        // Tauri main entry — generated by doql (Tauri v2)
        #![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

        fn main() {
            tauri::Builder::default()
                .run(tauri::generate_context!())
                .expect("error while running tauri application");
        }
    ''')


def _gen_build_rs() -> str:
    return textwrap.dedent('''\
        fn main() {
            tauri_build::build()
        }
    ''')


def _gen_package_json(spec: DoqlSpec) -> str:
    pkg_name = _snake(spec.app_name)
    return json.dumps({
        "name": f"{pkg_name}-desktop",
        "version": spec.version,
        "private": True,
        "scripts": {
            "dev": "tauri dev",
            "build": "tauri build",
            "tauri": "tauri",
        },
        "devDependencies": {
            "@tauri-apps/cli": "^2",
        },
    }, indent=2)


def generate(spec: DoqlSpec, env_vars: dict[str, str], out: pathlib.Path) -> None:
    """Generate desktop (Tauri) layer files into *out* directory."""
    desktop_iface = next((i for i in spec.interfaces if i.type in ("electron", "tauri")), None)
    if not desktop_iface:
        (out / "README.md").write_text(
            f"# {spec.app_name} — Desktop\n\nNo desktop interface (type: tauri|electron) defined.\n",
            encoding="utf-8",
        )
        print(f"    → desktop/README.md (skipped, no desktop interface)")
        return

    src_tauri = out / "src-tauri"
    src_dir = src_tauri / "src"
    icons_dir = src_tauri / "icons"
    for d in (src_tauri, src_dir, icons_dir):
        d.mkdir(parents=True, exist_ok=True)

    (out / "package.json").write_text(_gen_package_json(spec), encoding="utf-8")
    (src_tauri / "Cargo.toml").write_text(_gen_cargo_toml(spec), encoding="utf-8")
    (src_tauri / "tauri.conf.json").write_text(_gen_tauri_conf(spec), encoding="utf-8")
    (src_tauri / "build.rs").write_text(_gen_build_rs(), encoding="utf-8")
    (src_dir / "main.rs").write_text(_gen_main_rs(spec), encoding="utf-8")

    # Placeholder window icon — required by tauri::generate_context! at compile
    # time even when bundling is disabled. Replace with a real one for release.
    icon_path = icons_dir / "icon.png"
    if not icon_path.exists():
        icon_path.write_bytes(_make_solid_png(64, 64, (14, 165, 233)))

    print(f"    → desktop/package.json")
    print(f"    → desktop/src-tauri/Cargo.toml, tauri.conf.json, build.rs")
    print(f"    → desktop/src-tauri/src/main.rs")
    print(f"    → desktop/src-tauri/icons/icon.png (placeholder)")

    (out / "README.md").write_text(
        f"# {spec.app_name} — Desktop (Tauri v2)\n\n"
        f"Generated by `doql build`. Tauri 2.x shell wrapping the web frontend.\n\n"
        f"## Prerequisites\n\n"
        f"- **Rust** toolchain: <https://rustup.rs>\n"
        f"- **Node 20+** (for the web frontend)\n"
        f"- **System libraries** (Linux):\n"
        f"  ```bash\n"
        f"  sudo apt install -y \\\n"
        f"      libwebkit2gtk-4.1-dev libsoup-3.0-dev \\\n"
        f"      libgtk-3-dev libayatana-appindicator3-dev \\\n"
        f"      librsvg2-dev libssl-dev pkg-config build-essential\n"
        f"  ```\n\n"
        f"## Quick start\n\n"
        f"```bash\ncd build/desktop\nnpm install\nnpm run dev\n```\n\n"
        f"On first run cargo downloads ~300 deps (~3-5 min). Subsequent runs use the cache.\n\n"
        f"## Build installer\n\n"
        f"To produce `.deb`/`.AppImage`/`.dmg`/`.msi`, first add icons to `src-tauri/icons/`\n"
        f"and set `bundle.active = true` + populate `bundle.icon` in `tauri.conf.json`,\n"
        f"then:\n\n"
        f"```bash\nnpm run build\n# Artifacts in src-tauri/target/release/bundle/\n```\n",
        encoding="utf-8",
    )
    print(f"    → desktop/README.md")
