"""Generate rendered documents from DOCUMENT + TEMPLATE definitions.

Produces:
  build/documents/
  ├── <doc_name>.html        — rendered HTML from Jinja2 template
  └── render_<doc_name>.py   — CLI script to render with live data

Requires: jinja2 (included in doql deps).
Optional: weasyprint (for PDF output, user installs separately).
"""
from __future__ import annotations

import pathlib
import textwrap

from ..parser import DoqlSpec, Document, Template


def _find_template(spec: DoqlSpec, name: str) -> Template | None:
    for t in spec.templates:
        if t.name == name:
            return t
    return None


def _gen_render_script(doc: Document, spec: DoqlSpec) -> str:
    """Generate a standalone Python render script for one DOCUMENT."""
    return textwrap.dedent(f'''\
        #!/usr/bin/env python3
        """Render {doc.name} — generated by doql build.

        Usage:
            python render_{doc.name}.py [--pdf]

        Requires:
            pip install jinja2
            pip install weasyprint   # only if --pdf
        """
        import argparse
        import json
        import pathlib
        import sys

        try:
            from jinja2 import Environment, FileSystemLoader
        except ImportError:
            print("pip install jinja2", file=sys.stderr)
            sys.exit(1)


        PROJECT_ROOT = pathlib.Path(__file__).resolve().parent.parent.parent
        TEMPLATE = "{doc.template or ''}"
        OUTPUT_TYPE = "{doc.type}"


        def load_data():
            """Load stub data — replace with real DATA source integration."""
            return {{
                "app_name": "{spec.app_name}",
                "version": "{spec.version}",
                "document": "{doc.name}",
            }}


        def render_html(data: dict) -> str:
            template_path = PROJECT_ROOT / TEMPLATE
            if not template_path.exists():
                print(f"Template not found: {{template_path}}", file=sys.stderr)
                sys.exit(1)
            env = Environment(loader=FileSystemLoader(str(template_path.parent)))
            tmpl = env.get_template(template_path.name)
            return tmpl.render(**data)


        def render_pdf(html: str, output: pathlib.Path):
            try:
                from weasyprint import HTML
            except ImportError:
                print("pip install weasyprint  (for PDF output)", file=sys.stderr)
                sys.exit(1)
            HTML(string=html).write_pdf(str(output))


        def main():
            parser = argparse.ArgumentParser(description="Render {doc.name}")
            parser.add_argument("--pdf", action="store_true", help="Output PDF instead of HTML")
            parser.add_argument("-o", "--output", help="Output file path")
            args = parser.parse_args()

            data = load_data()
            html = render_html(data)

            if args.pdf or OUTPUT_TYPE == "pdf":
                out = pathlib.Path(args.output or "{doc.name}.pdf")
                render_pdf(html, out)
                print(f"PDF → {{out}}")
            else:
                out = pathlib.Path(args.output or "{doc.name}.html")
                out.write_text(html, encoding="utf-8")
                print(f"HTML → {{out}}")


        if __name__ == "__main__":
            main()
    ''')


def _gen_preview_html(doc: Document, spec: DoqlSpec, project_root: pathlib.Path | None) -> str:
    """Try to render a preview HTML from the template with stub data."""
    if not doc.template or not project_root:
        return f"<html><body><h1>{doc.name}</h1><p>No template configured.</p></body></html>"

    template_path = project_root / doc.template
    if not template_path.exists():
        return (
            f"<html><body><h1>{doc.name}</h1>"
            f"<p>Template not found: {doc.template}</p></body></html>"
        )

    try:
        from jinja2 import Environment, FileSystemLoader
        env = Environment(loader=FileSystemLoader(str(template_path.parent)))
        tmpl = env.get_template(template_path.name)
        # Render with empty/stub data — will show template structure
        stub = {
            "app_name": spec.app_name,
            "version": spec.version,
            "date": "2026-01-01",
            "month": "2026-01",
        }
        return tmpl.render(**stub)
    except ImportError:
        # jinja2 not installed — return raw template
        return template_path.read_text(encoding="utf-8")
    except Exception as e:
        return (
            f"<html><body><h1>{doc.name}</h1>"
            f"<p>Render error: {e}</p>"
            f"<pre>{template_path.read_text(encoding='utf-8')}</pre></body></html>"
        )


def generate(spec: DoqlSpec, env_vars: dict[str, str], out: pathlib.Path,
             project_root: pathlib.Path | None = None) -> None:
    """Generate document rendering pipeline into *out* directory."""
    if not spec.documents:
        print(f"    → documents/ (no DOCUMENTs defined, skipped)")
        return

    for doc in spec.documents:
        # Render script
        script_path = out / f"render_{doc.name}.py"
        script_path.write_text(_gen_render_script(doc, spec), encoding="utf-8")
        print(f"    → documents/render_{doc.name}.py")

        # Preview HTML
        preview = out / f"{doc.name}.html"
        preview.write_text(
            _gen_preview_html(doc, spec, project_root),
            encoding="utf-8",
        )
        print(f"    → documents/{doc.name}.html (preview)")

    # README
    readme = out / "README.md"
    readme.write_text(
        f"# {spec.app_name} — Documents\n\n"
        f"Generated by `doql build`.\n\n"
        f"## Documents\n\n"
        + "\n".join(
            f"- **{d.name}** ({d.type}) — `python render_{d.name}.py`"
            for d in spec.documents
        )
        + "\n\n"
        f"## Render\n\n"
        f"```bash\n"
        f"pip install jinja2 weasyprint\n"
        + "\n".join(f"python render_{d.name}.py --pdf" for d in spec.documents)
        + "\n```\n",
        encoding="utf-8",
    )
    print(f"    → documents/README.md")
