"""Generate docker-compose / quadlet / kiosk infra from DoqlSpec.

Produces:
  infra/
  ├── docker-compose.yml    — full compose with api + traefik + db
  ├── Dockerfile            — multi-stage Python build
  ├── .env.docker           — env vars for compose
  └── traefik.yml           — static Traefik config  (if traefik=true)

Or for quadlet:
  infra/
  ├── <app>.container        — Podman Quadlet unit
  ├── <app>-traefik.container
  └── <app>.env

Or for kiosk-appliance:
  infra/
  ├── install-kiosk.sh       — full installer (Openbox + Chromium + systemd)
  └── kiosk.service
"""
from __future__ import annotations

import pathlib
import textwrap

from ..parser import DoqlSpec


def _slug(name: str) -> str:
    return name.lower().replace(" ", "-").replace("_", "-")


# ────────────────────────────────────────────────────────
# docker-compose
# ────────────────────────────────────────────────────────

def _gen_docker_compose(spec: DoqlSpec, env_vars: dict[str, str], out: pathlib.Path) -> None:
    slug = _slug(spec.app_name)
    domain = spec.domain or env_vars.get("DOMAIN", f"{slug}.localhost")
    le_email = env_vars.get("LE_EMAIL", "ops@example.com")
    has_traefik = any(
        i.name == "web" or i.name == "api" for i in spec.interfaces
    )

    lines = [
        f"# Generated by doql build for {spec.app_name}",
        "services:",
        "",
        "  api:",
        f"    build:",
        f"      context: ../api",
        f"      dockerfile: ../infra/Dockerfile",
        f"    container_name: {slug}-api",
        f"    restart: unless-stopped",
        f"    env_file: .env.docker",
        f"    ports:",
        f"      - '8000:8000'",
        f"    volumes:",
        f"      - data:/app/data",
    ]
    if has_traefik:
        lines += [
            f"    labels:",
            f'      - "traefik.enable=true"',
            f'      - "traefik.http.routers.{slug}.rule=Host(`{domain}`)"',
            f'      - "traefik.http.routers.{slug}.tls.certresolver=letsencrypt"',
            f'      - "traefik.http.services.{slug}.loadbalancer.server.port=8000"',
        ]

    if has_traefik:
        lines += [
            "",
            "  traefik:",
            "    image: traefik:v3",
            "    container_name: traefik",
            "    restart: unless-stopped",
            "    command:",
            "      - --api.insecure=true",
            "      - --providers.docker=true",
            "      - --providers.docker.exposedbydefault=false",
            "      - --entrypoints.web.address=:80",
            "      - --entrypoints.websecure.address=:443",
            "      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web",
            f"      - --certificatesresolvers.letsencrypt.acme.email={le_email}",
            "      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json",
            "    ports:",
            "      - '80:80'",
            "      - '443:443'",
            "    volumes:",
            "      - /var/run/docker.sock:/var/run/docker.sock:ro",
            "      - letsencrypt:/letsencrypt",
        ]

    lines += [
        "",
        "volumes:",
        "  data:",
    ]
    if has_traefik:
        lines.append("  letsencrypt:")
    lines.append("")

    (out / "docker-compose.yml").write_text("\n".join(lines), encoding="utf-8")
    print(f"    → infra/docker-compose.yml")

    # Dockerfile
    dockerfile = textwrap.dedent(f"""\
        # Generated by doql build
        FROM python:3.13-slim AS base
        WORKDIR /app
        COPY requirements.txt .
        RUN pip install --no-cache-dir -r requirements.txt
        COPY . .
        EXPOSE 8000
        CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    """)
    (out / "Dockerfile").write_text(dockerfile, encoding="utf-8")
    print(f"    → infra/Dockerfile")

    # .env.docker
    env_lines = [f"# Environment for {spec.app_name} (docker-compose)"]
    env_lines.append(f"APP_NAME={spec.app_name}")
    env_lines.append(f"DATABASE_URL=sqlite:///./data/app.db")
    for ref in spec.env_refs:
        val = env_vars.get(ref, "")
        env_lines.append(f"{ref}={val}")
    env_lines.append("")
    (out / ".env.docker").write_text("\n".join(env_lines), encoding="utf-8")
    print(f"    → infra/.env.docker")


# ────────────────────────────────────────────────────────
# Podman Quadlet
# ────────────────────────────────────────────────────────

def _gen_quadlet(spec: DoqlSpec, env_vars: dict[str, str], out: pathlib.Path) -> None:
    slug = _slug(spec.app_name)
    domain = spec.domain or env_vars.get("DOMAIN", f"{slug}.localhost")
    le_email = env_vars.get("LE_EMAIL", "ops@example.com")
    rootless = spec.deploy.rootless

    # Main app container
    container = textwrap.dedent(f"""\
        # Generated by doql build — Podman Quadlet
        [Unit]
        Description={spec.app_name} API
        After=network-online.target

        [Container]
        Image=localhost/{slug}:latest
        PublishPort=8000:8000
        EnvironmentFile=%h/.config/containers/{slug}.env
        Volume={slug}-data:/app/data:Z
        {'Rootfs=true' if rootless else ''}

        [Service]
        Restart=always
        TimeoutStartSec=30

        [Install]
        WantedBy=default.target
    """)
    (out / f"{slug}.container").write_text(container, encoding="utf-8")
    print(f"    → infra/{slug}.container")

    # Traefik quadlet
    traefik = textwrap.dedent(f"""\
        # Generated by doql build — Traefik Quadlet
        [Unit]
        Description=Traefik reverse proxy for {spec.app_name}
        After=network-online.target

        [Container]
        Image=docker.io/library/traefik:v3
        PublishPort=80:80
        PublishPort=443:443
        Volume=/run/podman/podman.sock:/var/run/docker.sock:ro,z
        Volume={slug}-letsencrypt:/letsencrypt:Z
        Exec=--providers.docker=true \\
          --providers.docker.exposedbydefault=false \\
          --entrypoints.web.address=:80 \\
          --entrypoints.websecure.address=:443 \\
          --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web \\
          --certificatesresolvers.letsencrypt.acme.email={le_email} \\
          --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json

        [Service]
        Restart=always

        [Install]
        WantedBy=default.target
    """)
    (out / f"{slug}-traefik.container").write_text(traefik, encoding="utf-8")
    print(f"    → infra/{slug}-traefik.container")

    # .env file
    env_lines = [f"# Environment for {spec.app_name}"]
    env_lines.append(f"APP_NAME={spec.app_name}")
    env_lines.append(f"DOMAIN={domain}")
    env_lines.append(f"DATABASE_URL=sqlite:///./data/app.db")
    for ref in spec.env_refs:
        val = env_vars.get(ref, "")
        env_lines.append(f"{ref}={val}")
    env_lines.append("")
    (out / f"{slug}.env").write_text("\n".join(env_lines), encoding="utf-8")
    print(f"    → infra/{slug}.env")


# ────────────────────────────────────────────────────────
# Kiosk appliance
# ────────────────────────────────────────────────────────

def _gen_kiosk(spec: DoqlSpec, env_vars: dict[str, str], out: pathlib.Path) -> None:
    slug = _slug(spec.app_name)
    app_url = env_vars.get("KIOSK_URL", "http://localhost:8000")

    script = textwrap.dedent(f"""\
        #!/usr/bin/env bash
        # Generated by doql build — Kiosk appliance installer
        # Target: Raspberry Pi OS Lite 64-bit / any Debian-based
        set -euo pipefail

        APP_NAME="{spec.app_name}"
        KIOSK_URL="{app_url}"
        KIOSK_USER="kiosk"

        echo "🖥  Installing $APP_NAME kiosk..."

        # 1. System packages
        sudo apt-get update -qq
        sudo apt-get install -y -qq \\
            xserver-xorg xinit openbox \\
            chromium-browser \\
            unclutter \\
            lightdm \\
            pulseaudio

        # 2. Create kiosk user
        if ! id "$KIOSK_USER" &>/dev/null; then
            sudo useradd -m -s /bin/bash "$KIOSK_USER"
        fi

        # 3. Openbox autostart → Chromium kiosk
        sudo mkdir -p /home/$KIOSK_USER/.config/openbox
        cat <<'AUTOSTART' | sudo tee /home/$KIOSK_USER/.config/openbox/autostart
        # Hide cursor after 5s idle
        unclutter -idle 5 -root &

        # Disable screen blanking
        xset s off
        xset -dpms
        xset s noblank

        # Start Chromium in kiosk mode
        chromium-browser \\
            --noerrdialogs \\
            --disable-infobars \\
            --kiosk \\
            --disable-translate \\
            --disable-features=TranslateUI \\
            --overscroll-history-navigation=0 \\
            "$KIOSK_URL"
        AUTOSTART
        sudo chown -R $KIOSK_USER:$KIOSK_USER /home/$KIOSK_USER/.config

        # 4. LightDM autologin
        sudo mkdir -p /etc/lightdm/lightdm.conf.d
        cat <<EOF | sudo tee /etc/lightdm/lightdm.conf.d/50-kiosk.conf
        [Seat:*]
        autologin-user=$KIOSK_USER
        autologin-session=openbox
        EOF

        # 5. Systemd service for the API backend
        sudo cp "$(dirname "$0")/kiosk.service" /etc/systemd/system/{slug}.service
        sudo systemctl daemon-reload
        sudo systemctl enable {slug}.service

        echo "✅ Kiosk installed. Reboot to start."
    """)
    (out / "install-kiosk.sh").write_text(script, encoding="utf-8")
    print(f"    → infra/install-kiosk.sh")

    # systemd service
    service = textwrap.dedent(f"""\
        # Generated by doql build
        [Unit]
        Description={spec.app_name} backend
        After=network-online.target

        [Service]
        Type=simple
        User=kiosk
        WorkingDirectory=/opt/{slug}
        ExecStart=/opt/{slug}/venv/bin/uvicorn main:app --host 0.0.0.0 --port 8000
        Restart=always
        RestartSec=5

        [Install]
        WantedBy=multi-user.target
    """)
    (out / "kiosk.service").write_text(service, encoding="utf-8")
    print(f"    → infra/kiosk.service")


# ────────────────────────────────────────────────────────
# Public API
# ────────────────────────────────────────────────────────

def generate(spec: DoqlSpec, env_vars: dict[str, str], out: pathlib.Path) -> None:
    """Generate infra layer files into *out* directory."""
    target = spec.deploy.target

    if target == "docker-compose":
        _gen_docker_compose(spec, env_vars, out)
    elif target == "quadlet":
        _gen_quadlet(spec, env_vars, out)
    elif target == "kiosk-appliance":
        _gen_kiosk(spec, env_vars, out)
    else:
        _gen_docker_compose(spec, env_vars, out)
