"""Generate docker-compose / quadlet / kiosk infra from DoqlSpec.

Produces:
  infra/
  ├── docker-compose.yml    — full compose with api + traefik + db
  ├── Dockerfile            — multi-stage Python build
  ├── .env.docker           — env vars for compose
  └── traefik.yml           — static Traefik config  (if traefik=true)

Or for quadlet:
  infra/
  ├── <app>.container        — Podman Quadlet unit
  ├── <app>-traefik.container
  └── <app>.env

Or for kiosk-appliance:
  infra/
  ├── install-kiosk.sh       — full installer (Openbox + Chromium + systemd)
  └── kiosk.service
"""
from __future__ import annotations

import pathlib
import textwrap

from ..parser import DoqlSpec


def _slug(name: str) -> str:
    return name.lower().replace(" ", "-").replace("_", "-")


# ────────────────────────────────────────────────────────
# docker-compose
# ────────────────────────────────────────────────────────

def _gen_docker_compose(spec: DoqlSpec, env_vars: dict[str, str], out: pathlib.Path) -> None:
    slug = _slug(spec.app_name)
    domain = spec.domain or env_vars.get("DOMAIN", f"{slug}.localhost")
    le_email = env_vars.get("LE_EMAIL", "ops@example.com")
    has_traefik = any(
        i.name == "web" or i.name == "api" for i in spec.interfaces
    )

    lines = [
        f"# Generated by doql build for {spec.app_name}",
        "services:",
        "",
        "  api:",
        f"    build:",
        f"      context: ../api",
        f"      dockerfile: ../infra/Dockerfile",
        f"    container_name: {slug}-api",
        f"    restart: unless-stopped",
        f"    env_file: .env.docker",
        f"    ports:",
        f"      - '8000:8000'",
        f"    volumes:",
        f"      - data:/app/data",
    ]
    if has_traefik:
        lines += [
            f"    labels:",
            f'      - "traefik.enable=true"',
            f'      - "traefik.http.routers.{slug}.rule=Host(`{domain}`)"',
            f'      - "traefik.http.routers.{slug}.tls.certresolver=letsencrypt"',
            f'      - "traefik.http.services.{slug}.loadbalancer.server.port=8000"',
        ]

    if has_traefik:
        lines += [
            "",
            "  traefik:",
            "    image: traefik:v3",
            "    container_name: traefik",
            "    restart: unless-stopped",
            "    command:",
            "      - --api.insecure=true",
            "      - --providers.docker=true",
            "      - --providers.docker.exposedbydefault=false",
            "      - --entrypoints.web.address=:80",
            "      - --entrypoints.websecure.address=:443",
            "      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web",
            f"      - --certificatesresolvers.letsencrypt.acme.email={le_email}",
            "      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json",
            "    ports:",
            "      - '80:80'",
            "      - '443:443'",
            "    volumes:",
            "      - /var/run/docker.sock:/var/run/docker.sock:ro",
            "      - letsencrypt:/letsencrypt",
        ]

    lines += [
        "",
        "volumes:",
        "  data:",
    ]
    if has_traefik:
        lines.append("  letsencrypt:")
    lines.append("")

    (out / "docker-compose.yml").write_text("\n".join(lines), encoding="utf-8")
    print(f"    → infra/docker-compose.yml")

    # Dockerfile
    dockerfile = textwrap.dedent(f"""\
        # Generated by doql build
        FROM python:3.13-slim AS base
        WORKDIR /app
        COPY requirements.txt .
        RUN pip install --no-cache-dir -r requirements.txt
        COPY . .
        EXPOSE 8000
        CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    """)
    (out / "Dockerfile").write_text(dockerfile, encoding="utf-8")
    print(f"    → infra/Dockerfile")

    # .env.docker
    env_lines = [f"# Environment for {spec.app_name} (docker-compose)"]
    env_lines.append(f"APP_NAME={spec.app_name}")
    env_lines.append(f"DATABASE_URL=sqlite:///./data/app.db")
    for ref in spec.env_refs:
        val = env_vars.get(ref, "")
        env_lines.append(f"{ref}={val}")
    env_lines.append("")
    (out / ".env.docker").write_text("\n".join(env_lines), encoding="utf-8")
    print(f"    → infra/.env.docker")


# ────────────────────────────────────────────────────────
# Podman Quadlet
# ────────────────────────────────────────────────────────

def _gen_quadlet(spec: DoqlSpec, env_vars: dict[str, str], out: pathlib.Path) -> None:
    slug = _slug(spec.app_name)
    domain = spec.domain or env_vars.get("DOMAIN", f"{slug}.localhost")
    le_email = env_vars.get("LE_EMAIL", "ops@example.com")
    rootless = spec.deploy.rootless

    # Main app container
    container = textwrap.dedent(f"""\
        # Generated by doql build — Podman Quadlet
        [Unit]
        Description={spec.app_name} API
        After=network-online.target

        [Container]
        Image=localhost/{slug}:latest
        PublishPort=8000:8000
        EnvironmentFile=%h/.config/containers/{slug}.env
        Volume={slug}-data:/app/data:Z
        {'Rootfs=true' if rootless else ''}

        [Service]
        Restart=always
        TimeoutStartSec=30

        [Install]
        WantedBy=default.target
    """)
    (out / f"{slug}.container").write_text(container, encoding="utf-8")
    print(f"    → infra/{slug}.container")

    # Traefik quadlet
    traefik = textwrap.dedent(f"""\
        # Generated by doql build — Traefik Quadlet
        [Unit]
        Description=Traefik reverse proxy for {spec.app_name}
        After=network-online.target

        [Container]
        Image=docker.io/library/traefik:v3
        PublishPort=80:80
        PublishPort=443:443
        Volume=/run/podman/podman.sock:/var/run/docker.sock:ro,z
        Volume={slug}-letsencrypt:/letsencrypt:Z
        Exec=--providers.docker=true \\
          --providers.docker.exposedbydefault=false \\
          --entrypoints.web.address=:80 \\
          --entrypoints.websecure.address=:443 \\
          --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web \\
          --certificatesresolvers.letsencrypt.acme.email={le_email} \\
          --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json

        [Service]
        Restart=always

        [Install]
        WantedBy=default.target
    """)
    (out / f"{slug}-traefik.container").write_text(traefik, encoding="utf-8")
    print(f"    → infra/{slug}-traefik.container")

    # .env file
    env_lines = [f"# Environment for {spec.app_name}"]
    env_lines.append(f"APP_NAME={spec.app_name}")
    env_lines.append(f"DOMAIN={domain}")
    env_lines.append(f"DATABASE_URL=sqlite:///./data/app.db")
    for ref in spec.env_refs:
        val = env_vars.get(ref, "")
        env_lines.append(f"{ref}={val}")
    env_lines.append("")
    (out / f"{slug}.env").write_text("\n".join(env_lines), encoding="utf-8")
    print(f"    → infra/{slug}.env")


# ────────────────────────────────────────────────────────
# Kiosk appliance
# ────────────────────────────────────────────────────────

def _gen_kiosk(spec: DoqlSpec, env_vars: dict[str, str], out: pathlib.Path) -> None:
    slug = _slug(spec.app_name)
    app_url = env_vars.get("KIOSK_URL", "http://localhost:8000")

    script = textwrap.dedent(f"""\
        #!/usr/bin/env bash
        # Generated by doql build — Kiosk appliance installer
        # Target: Raspberry Pi OS Lite 64-bit / any Debian-based
        set -euo pipefail

        APP_NAME="{spec.app_name}"
        KIOSK_URL="{app_url}"
        KIOSK_USER="kiosk"

        echo "🖥  Installing $APP_NAME kiosk..."

        # 1. System packages
        sudo apt-get update -qq
        sudo apt-get install -y -qq \\
            xserver-xorg xinit openbox \\
            chromium-browser \\
            unclutter \\
            lightdm \\
            pulseaudio

        # 2. Create kiosk user
        if ! id "$KIOSK_USER" &>/dev/null; then
            sudo useradd -m -s /bin/bash "$KIOSK_USER"
        fi

        # 3. Openbox autostart → Chromium kiosk
        sudo mkdir -p /home/$KIOSK_USER/.config/openbox
        cat <<'AUTOSTART' | sudo tee /home/$KIOSK_USER/.config/openbox/autostart
        # Hide cursor after 5s idle
        unclutter -idle 5 -root &

        # Disable screen blanking
        xset s off
        xset -dpms
        xset s noblank

        # Start Chromium in kiosk mode
        chromium-browser \\
            --noerrdialogs \\
            --disable-infobars \\
            --kiosk \\
            --disable-translate \\
            --disable-features=TranslateUI \\
            --overscroll-history-navigation=0 \\
            "$KIOSK_URL"
        AUTOSTART
        sudo chown -R $KIOSK_USER:$KIOSK_USER /home/$KIOSK_USER/.config

        # 4. LightDM autologin
        sudo mkdir -p /etc/lightdm/lightdm.conf.d
        cat <<EOF | sudo tee /etc/lightdm/lightdm.conf.d/50-kiosk.conf
        [Seat:*]
        autologin-user=$KIOSK_USER
        autologin-session=openbox
        EOF

        # 5. Systemd service for the API backend
        sudo cp "$(dirname "$0")/kiosk.service" /etc/systemd/system/{slug}.service
        sudo systemctl daemon-reload
        sudo systemctl enable {slug}.service

        echo "✅ Kiosk installed. Reboot to start."
    """)
    (out / "install-kiosk.sh").write_text(script, encoding="utf-8")
    print(f"    → infra/install-kiosk.sh")

    # systemd service
    service = textwrap.dedent(f"""\
        # Generated by doql build
        [Unit]
        Description={spec.app_name} backend
        After=network-online.target

        [Service]
        Type=simple
        User=kiosk
        WorkingDirectory=/opt/{slug}
        ExecStart=/opt/{slug}/venv/bin/uvicorn main:app --host 0.0.0.0 --port 8000
        Restart=always
        RestartSec=5

        [Install]
        WantedBy=multi-user.target
    """)
    (out / "kiosk.service").write_text(service, encoding="utf-8")
    print(f"    → infra/kiosk.service")


# ────────────────────────────────────────────────────────
# Public API
# ────────────────────────────────────────────────────────

def _map_deploy_strategy(doql_target: str) -> str:
    """Map doql DEPLOY.target to redeploy DeployStrategy value."""
    return {
        "docker-compose": "docker_full",
        "quadlet":        "podman_quadlet",
        "kubernetes":     "k3s",
        "kiosk-appliance": "podman_quadlet",
        "systemd":        "systemd",
    }.get(doql_target, "docker_full")


# ────────────────────────────────────────────────────────
# Kubernetes
# ────────────────────────────────────────────────────────

def _gen_kubernetes(spec: DoqlSpec, env_vars: dict[str, str], out: pathlib.Path) -> None:
    slug = _slug(spec.app_name)
    domain = spec.domain or env_vars.get("DOMAIN", f"{slug}.localhost")
    replicas = 1
    for infra in spec.infrastructures:
        if infra.type in ("kubernetes", "k8s", "k3s"):
            replicas = infra.replicas or 1
            break

    deployment = textwrap.dedent(f"""\
        # Generated by doql build — Kubernetes manifest
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: {slug}
          labels:
            app: {slug}
        spec:
          replicas: {replicas}
          selector:
            matchLabels:
              app: {slug}
          template:
            metadata:
              labels:
                app: {slug}
            spec:
              containers:
                - name: api
                  image: "{slug}:latest"
                  ports:
                    - containerPort: 8000
                  envFrom:
                    - configMapRef:
                        name: {slug}-config
                  volumeMounts:
                    - name: data
                      mountPath: /app/data
              volumes:
                - name: data
                  emptyDir: {{}}
    """)
    (out / "deployment.yaml").write_text(deployment, encoding="utf-8")
    print(f"    → infra/deployment.yaml")

    service = textwrap.dedent(f"""\
        apiVersion: v1
        kind: Service
        metadata:
          name: {slug}
        spec:
          selector:
            app: {slug}
          ports:
            - port: 8000
              targetPort: 8000
    """)
    (out / "service.yaml").write_text(service, encoding="utf-8")
    print(f"    → infra/service.yaml")

    config = textwrap.dedent(f"""\
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: {slug}-config
        data:
          APP_NAME: "{spec.app_name}"
          DATABASE_URL: "sqlite:///./data/app.db"
    """)
    for ref in spec.env_refs:
        val = env_vars.get(ref, "")
        config = config.rstrip() + f'\n  {ref}: "{val}"\n'
    (out / "configmap.yaml").write_text(config, encoding="utf-8")
    print(f"    → infra/configmap.yaml")

    ingress = textwrap.dedent(f"""\
        apiVersion: networking.k8s.io/v1
        kind: Ingress
        metadata:
          name: {slug}
          annotations:
            traefik.ingress.kubernetes.io/router.tls: "true"
        spec:
          rules:
            - host: {domain}
              http:
                paths:
                  - path: /
                    pathType: Prefix
                    backend:
                      service:
                        name: {slug}
                        port:
                          number: 8000
    """)
    (out / "ingress.yaml").write_text(ingress, encoding="utf-8")
    print(f"    → infra/ingress.yaml")

    kustomize = textwrap.dedent("""\
        apiVersion: kustomize.config.k8s.io/v1beta1
        kind: Kustomization
        resources:
          - deployment.yaml
          - service.yaml
          - configmap.yaml
          - ingress.yaml
    """)
    (out / "kustomization.yaml").write_text(kustomize, encoding="utf-8")
    print(f"    → infra/kustomization.yaml")


# ────────────────────────────────────────────────────────
# Terraform
# ────────────────────────────────────────────────────────

def _gen_terraform(spec: DoqlSpec, env_vars: dict[str, str], out: pathlib.Path) -> None:
    slug = _slug(spec.app_name)
    main_tf = textwrap.dedent(f'''\
        # Generated by doql build — Terraform infrastructure
        terraform {{
          required_providers {{
            docker = {{
              source  = "kreuzwerker/docker"
              version = "~> 3.0"
            }}
          }}
        }}

        provider "docker" {{}}

        resource "docker_image" "{slug}" {{
          name = "{slug}:latest"
          keep_locally = true
        }}

        resource "docker_container" "{slug}" {{
          name  = "{slug}-api"
          image = docker_image.{slug}.name
          ports {{
            internal = 8000
            external = 8000
          }}
          env = [
            "APP_NAME={spec.app_name}",
          ]
        }}
    ''')
    (out / "main.tf").write_text(main_tf, encoding="utf-8")
    print(f"    → infra/main.tf")

    variables_tf = textwrap.dedent("""\
        variable "domain" {
          description = "Application domain"
          type        = string
          default     = "localhost"
        }

        variable "replicas" {
          description = "Number of replicas"
          type        = number
          default     = 1
        }
    """)
    (out / "variables.tf").write_text(variables_tf, encoding="utf-8")
    print(f"    → infra/variables.tf")

    outputs_tf = textwrap.dedent(f'''\
        output "container_name" {{
          value = docker_container.{slug}.name
        }}
    ''')
    (out / "outputs.tf").write_text(outputs_tf, encoding="utf-8")
    print(f"    → infra/outputs.tf")


# ────────────────────────────────────────────────────────
# Nginx
# ────────────────────────────────────────────────────────

def _gen_nginx(spec: DoqlSpec, env_vars: dict[str, str], out: pathlib.Path) -> None:
    slug = _slug(spec.app_name)
    domain = spec.domain or env_vars.get("DOMAIN", f"{slug}.localhost")
    upstream = "localhost:8000"
    tls_block = ""
    for ing in spec.ingresses:
        if ing.tls:
            tls_block = textwrap.dedent(f"""\
                listen 443 ssl;
                ssl_certificate /etc/nginx/ssl/{slug}.crt;
                ssl_certificate_key /etc/nginx/ssl/{slug}.key;
            """)
            break

    conf = textwrap.dedent(f'''\
        # Generated by doql build — Nginx reverse proxy
        upstream {slug}_api {{
            server {upstream};
        }}

        server {{
            listen 80;
            server_name {domain};
            {tls_block}

            location / {{
                proxy_pass http://{slug}_api;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }}
        }}
    ''')
    (out / "nginx.conf").write_text(conf, encoding="utf-8")
    print(f"    → infra/nginx.conf")

    dockerfile_nginx = textwrap.dedent("""\
        FROM nginx:alpine
        COPY nginx.conf /etc/nginx/conf.d/default.conf
        EXPOSE 80 443
    """)
    (out / "Dockerfile.nginx").write_text(dockerfile_nginx, encoding="utf-8")
    print(f"    → infra/Dockerfile.nginx")


def _gen_migration_spec(spec: DoqlSpec, env_vars: dict[str, str], out: pathlib.Path) -> None:
    """Generate redeploy migration.yaml alongside docker-compose/quadlet artifacts.

    Allows ``redeploy run`` (no args) to deploy what ``doql build`` generated.
    Requires: pip install doql[deploy]  (installs redeploy>=0.1.2)
    """
    import yaml as _yaml

    slug = _slug(spec.app_name)
    domain = spec.domain or env_vars.get("DOMAIN", f"{slug}.example.com")
    host = env_vars.get("DEPLOY_HOST", "local")
    version = spec.version or "0.1.0"
    target_strategy = _map_deploy_strategy(spec.deploy.target)
    verify_url = (
        env_vars.get("VERIFY_URL")
        or (f"https://{domain}/api/health" if host != "local" else f"http://localhost:8000/api/health")
    )

    migration: dict = {
        "name": slug,
        "description": f"Deploy {spec.app_name} — generated by doql build",
        "source": {
            "strategy": "docker_full",
            "host": "local",
            "app": slug,
            "version": version,
        },
        "target": {
            "strategy": target_strategy,
            "host": host,
            "app": slug,
            "version": version,
            "domain": domain,
            "remote_dir": env_vars.get("REMOTE_DIR", f"/opt/{slug}"),
            "env_file": ".env",
            "verify_url": verify_url,
            "verify_version": version[:3],
        },
        "notes": [
            f"Generated by doql build from {spec.app_name} DEPLOY: target: {spec.deploy.target}",
            f"Run: redeploy run --plan-only   (preview steps)",
            f"Run: redeploy run --dry-run     (dry run)",
            f"Run: redeploy run               (deploy!)",
            f"Set DEPLOY_HOST=user@VPS_IP before building to embed VPS address.",
        ],
    }

    # For kiosk: point to the install script generated by _gen_kiosk
    if spec.deploy.target == "kiosk-appliance":
        migration["extra_steps"] = [
            {
                "id": "run_kiosk_installer",
                "action": "ssh_cmd",
                "description": "Run doql-generated kiosk install script",
                "command": f"bash /opt/{slug}/infra/install-kiosk.sh",
                "risk": "medium",
            }
        ]

    dest = out / "migration.yaml"
    dest.write_text(_yaml.dump(migration, allow_unicode=True, sort_keys=False), encoding="utf-8")
    print(f"    → infra/migration.yaml  (redeploy spec)")


def generate(spec: DoqlSpec, env_vars: dict[str, str], out: pathlib.Path) -> None:
    """Generate infra layer files into *out* directory."""
    # Prefer explicit Infrastructure blocks over legacy deploy.target
    infra_types = {i.type for i in spec.infrastructures}
    ingress_types = {i.type for i in spec.ingresses}

    # Fallback to legacy deploy.target if no Infrastructure blocks declared
    if not infra_types:
        infra_types = {spec.deploy.target}

    for itype in infra_types:
        if itype in ("docker-compose", "docker"):
            _gen_docker_compose(spec, env_vars, out)
        elif itype == "quadlet":
            _gen_quadlet(spec, env_vars, out)
        elif itype == "kiosk-appliance":
            _gen_kiosk(spec, env_vars, out)
        elif itype in ("kubernetes", "k8s", "k3s"):
            _gen_kubernetes(spec, env_vars, out)
        elif itype == "terraform":
            _gen_terraform(spec, env_vars, out)
        else:
            _gen_docker_compose(spec, env_vars, out)

    # Nginx config if requested via Ingress block
    if "nginx" in ingress_types:
        _gen_nginx(spec, env_vars, out)

    # Always emit migration.yaml for redeploy (doql[deploy])
    _gen_migration_spec(spec, env_vars, out)
