"""Generate docker-compose / quadlet / kiosk infra from DoqlSpec."""
from __future__ import annotations

import pathlib

from ..parser import DoqlSpec


def generate(spec: DoqlSpec, env_vars: dict[str, str], out: pathlib.Path) -> None:
    """Generate infra layer files into *out* directory."""
    target = spec.deploy.target

    if target == "docker-compose":
        _gen_docker_compose(spec, env_vars, out)
    elif target == "quadlet":
        _gen_quadlet(spec, env_vars, out)
    elif target == "kiosk-appliance":
        _gen_kiosk(spec, env_vars, out)
    else:
        _gen_docker_compose(spec, env_vars, out)

    print(f"    → infra/{target} (stub)")


def _gen_docker_compose(spec: DoqlSpec, env_vars: dict[str, str], out: pathlib.Path) -> None:
    compose = out / "docker-compose.yml"
    compose.write_text(
        f"# Generated by doql build for {spec.app_name}\n"
        f"# Target: docker-compose\n"
        f"version: '3.8'\n"
        f"services:\n"
        f"  api:\n"
        f"    build: ../api\n"
        f"    ports:\n"
        f"      - '8000:8000'\n",
        encoding="utf-8",
    )


def _gen_quadlet(spec: DoqlSpec, env_vars: dict[str, str], out: pathlib.Path) -> None:
    container = out / f"{spec.app_name.lower().replace(' ', '-')}.container"
    container.write_text(
        f"# Generated by doql build — Podman Quadlet\n"
        f"[Container]\n"
        f"Image=localhost/{spec.app_name.lower().replace(' ', '-')}:latest\n"
        f"PublishPort=8000:8000\n\n"
        f"[Service]\n"
        f"Restart=always\n\n"
        f"[Install]\n"
        f"WantedBy=default.target\n",
        encoding="utf-8",
    )


def _gen_kiosk(spec: DoqlSpec, env_vars: dict[str, str], out: pathlib.Path) -> None:
    script = out / "install-kiosk.sh"
    script.write_text(
        f"#!/usr/bin/env bash\n"
        f"# Generated by doql build — Kiosk appliance installer\n"
        f"# Target: Raspberry Pi OS Lite 64-bit\n"
        f"set -euo pipefail\n\n"
        f'echo "Installing {spec.app_name} kiosk..."\n'
        f"# TODO: Faza 2 — Openbox autostart, chromium --kiosk, udev rules\n"
        f'echo "Done (stub)."\n',
        encoding="utf-8",
    )
