"""Generate integration service modules from INTEGRATION section.

Produces:
  build/api/services/
  ├── __init__.py
  ├── email_service.py      — SMTP send via env vars
  ├── slack_service.py      — webhook notifications
  ├── storage_service.py    — S3-compatible file storage
  ├── notifications.py      — unified notify()
  └── README.md
"""
from __future__ import annotations

import pathlib
import textwrap

from ..parser import DoqlSpec


def _gen_email_service() -> str:
    return textwrap.dedent('''\
        """Email service — generated by doql."""
        import os
        import smtplib
        from email.mime.text import MIMEText
        from email.mime.multipart import MIMEMultipart

        SMTP_HOST = os.getenv("SMTP_HOST", "localhost")
        SMTP_PORT = int(os.getenv("SMTP_PORT", "587"))
        SMTP_USER = os.getenv("SMTP_USER", "")
        SMTP_PASS = os.getenv("SMTP_PASS", "")
        SMTP_FROM = os.getenv("SMTP_FROM", "noreply@example.com")


        def send_email(to: str | list[str], subject: str, body: str, html: bool = False) -> bool:
            """Send an email. Returns True on success."""
            if isinstance(to, str):
                to = [to]
            msg = MIMEMultipart("alternative")
            msg["Subject"] = subject
            msg["From"] = SMTP_FROM
            msg["To"] = ", ".join(to)
            content_type = "html" if html else "plain"
            msg.attach(MIMEText(body, content_type))
            try:
                with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
                    if SMTP_USER:
                        server.starttls()
                        server.login(SMTP_USER, SMTP_PASS)
                    server.sendmail(SMTP_FROM, to, msg.as_string())
                return True
            except Exception as e:
                print(f"Email error: {e}")
                return False
    ''')


def _gen_slack_service() -> str:
    return textwrap.dedent('''\
        """Slack webhook service — generated by doql."""
        import json
        import os
        import urllib.request

        SLACK_WEBHOOK = os.getenv("SLACK_WEBHOOK", "")


        def send_slack(message: str, channel: str | None = None) -> bool:
            """Send a message to Slack via webhook. Returns True on success."""
            if not SLACK_WEBHOOK:
                print("SLACK_WEBHOOK not configured")
                return False
            payload = {"text": message}
            if channel:
                payload["channel"] = channel
            try:
                req = urllib.request.Request(
                    SLACK_WEBHOOK,
                    data=json.dumps(payload).encode(),
                    headers={"Content-Type": "application/json"},
                )
                with urllib.request.urlopen(req) as resp:
                    return resp.status == 200
            except Exception as e:
                print(f"Slack error: {e}")
                return False
    ''')


def _gen_storage_service() -> str:
    return textwrap.dedent('''\
        """S3-compatible storage service — generated by doql."""
        import os

        S3_ENDPOINT = os.getenv("S3_ENDPOINT", "")
        S3_BUCKET = os.getenv("S3_BUCKET", "")
        S3_ACCESS_KEY = os.getenv("S3_ACCESS_KEY", os.getenv("AWS_ACCESS_KEY_ID", ""))
        S3_SECRET_KEY = os.getenv("S3_SECRET_KEY", os.getenv("AWS_SECRET_ACCESS_KEY", ""))
        S3_REGION = os.getenv("S3_REGION", "us-east-1")


        def get_client():
            """Get boto3 S3 client. Requires: pip install boto3"""
            import boto3
            kwargs = {"region_name": S3_REGION}
            if S3_ENDPOINT:
                kwargs["endpoint_url"] = S3_ENDPOINT
            if S3_ACCESS_KEY:
                kwargs["aws_access_key_id"] = S3_ACCESS_KEY
                kwargs["aws_secret_access_key"] = S3_SECRET_KEY
            return boto3.client("s3", **kwargs)


        def upload_file(local_path: str, key: str, bucket: str | None = None) -> str:
            """Upload a file to S3. Returns the key."""
            client = get_client()
            client.upload_file(local_path, bucket or S3_BUCKET, key)
            return key


        def download_file(key: str, local_path: str, bucket: str | None = None) -> str:
            """Download a file from S3. Returns local path."""
            client = get_client()
            client.download_file(bucket or S3_BUCKET, key, local_path)
            return local_path


        def get_presigned_url(key: str, expires: int = 3600, bucket: str | None = None) -> str:
            """Generate a presigned URL for a file."""
            client = get_client()
            return client.generate_presigned_url(
                "get_object",
                Params={"Bucket": bucket or S3_BUCKET, "Key": key},
                ExpiresIn=expires,
            )
    ''')


def _gen_notifications(integrations: list[str]) -> str:
    """Unified notification dispatcher."""
    has_email = "notifications" in integrations or "email" in integrations
    has_slack = "notifications" in integrations or "slack" in integrations

    lines = [
        '"""Unified notification service — generated by doql."""',
    ]
    if has_email:
        lines.append('from services.email_service import send_email')
    if has_slack:
        lines.append('from services.slack_service import send_slack')
    lines.append('')
    lines.append('')
    lines.append('def notify(message: str, recipients: list[str] | None = None, channels: list[str] | None = None):')
    lines.append('    """Send notification via all configured channels."""')
    lines.append('    results = {}')
    if has_email:
        lines.append('    if recipients:')
        lines.append('        results["email"] = send_email(recipients, "Notification", message)')
    if has_slack:
        lines.append('    results["slack"] = send_slack(message)')
    lines.append('    return results')
    lines.append('')
    return '\n'.join(lines)


def _gen_api_client(client) -> str:
    """Generate a typed REST API client for an API_CLIENT declaration."""
    return textwrap.dedent(f'''\
        """API client: {client.name} — generated by doql."""
        import os
        import json
        import urllib.request
        import urllib.error
        from typing import Any, Optional

        BASE_URL = os.getenv("{client.name.upper()}_BASE_URL", "{client.base_url or 'http://localhost:8000'}")
        AUTH_TOKEN = os.getenv("{client.name.upper()}_TOKEN", "{client.token or ''}")
        TIMEOUT = {int(client.timeout.rstrip('s')) if client.timeout else 30}
        MAX_RETRIES = {client.retry}


        def _request(method: str, path: str, data: Optional[dict] = None) -> dict:
            url = f"{{BASE_URL}}{{path}}"
            body = json.dumps(data).encode() if data else None
            headers = {{
                "Content-Type": "application/json",
                "Accept": "application/json",
            }}
            if AUTH_TOKEN:
                headers["Authorization"] = f"Bearer {{AUTH_TOKEN}}"
            req = urllib.request.Request(url, data=body, headers=headers, method=method)
            for attempt in range(MAX_RETRIES + 1):
                try:
                    with urllib.request.urlopen(req, timeout=TIMEOUT) as resp:
                        return json.loads(resp.read().decode())
                except urllib.error.HTTPError as e:
                    if attempt == MAX_RETRIES:
                        raise
                    import time; time.sleep(2 ** attempt)
                except urllib.error.URLError as e:
                    if attempt == MAX_RETRIES:
                        raise
                    import time; time.sleep(2 ** attempt)
            return {{}}


        def get(path: str) -> dict:
            return _request("GET", path)


        def post(path: str, data: dict) -> dict:
            return _request("POST", path, data)


        def patch(path: str, data: dict) -> dict:
            return _request("PATCH", path, data)


        def delete(path: str) -> dict:
            return _request("DELETE", path)
    ''')


def _gen_webhook_dispatcher(webhooks: list) -> str:
    """Generate a FastAPI webhook receiver + dispatcher."""
    lines = [
        '"""Webhook dispatcher — generated by doql."""',
        'import hashlib',
        'import hmac',
        'import os',
        'from typing import Any',
        '',
        'from fastapi import APIRouter, Request, HTTPException',
        '',
        'router = APIRouter(prefix="/webhooks", tags=["webhooks"])',
        '',
        '',
        'WEBHOOK_HANDLERS: dict[str, list] = {}',
        '',
        '',
        'def on_webhook(event: str):',
        '    """Decorator to register a webhook handler."""',
        '    def decorator(fn):',
        '        WEBHOOK_HANDLERS.setdefault(event, []).append(fn)',
        '        return fn',
        '    return decorator',
        '',
        '',
        'def _verify_signature(payload: bytes, signature: str, secret: str) -> bool:',
        '    expected = hmac.new(secret.encode(), payload, hashlib.sha256).hexdigest()',
        '    return hmac.compare_digest(expected, signature)',
        '',
        '',
    ]
    for wh in webhooks:
        secret_env = f"{wh.name.upper()}_WEBHOOK_SECRET"
        lines.append(f'@router.post("/{wh.name}")')
        lines.append(f'async def handle_{wh.name}(request: Request):')
        lines.append(f'    """Receive {wh.name} webhook (source={wh.source or "any"}, event={wh.event or "any"})."""')
        lines.append(f'    body = await request.body()')
        lines.append(f'    secret = os.getenv("{secret_env}", "")')
        lines.append(f'    if secret:')
        lines.append(f'        sig = request.headers.get("X-Signature", "")')
        lines.append(f'        if not _verify_signature(body, sig, secret):')
        lines.append(f'            raise HTTPException(401, "Invalid signature")')
        lines.append(f'    import json')
        lines.append(f'    payload = json.loads(body) if body else {{}}')
        lines.append(f'    handlers = WEBHOOK_HANDLERS.get("{wh.event or wh.name}", [])')
        lines.append(f'    results = []')
        lines.append(f'    for handler in handlers:')
        lines.append(f'        results.append(handler(payload))')
        lines.append(f'    return {{"status": "ok", "handlers_called": len(results)}}')
        lines.append('')
        lines.append('')

    return '\n'.join(lines)


def _setup_services_dir(out: pathlib.Path) -> pathlib.Path:
    """Create services directory and __init__.py."""
    services_dir = out
    services_dir.mkdir(parents=True, exist_ok=True)
    (services_dir / "__init__.py").write_text("", encoding="utf-8")
    return services_dir


def _generate_integration_services(integrations: list[str], services_dir: pathlib.Path, generated: list[str]) -> None:
    """Generate integration service files (email, slack, storage, notifications)."""
    if any(i in integrations for i in ("notifications", "email")):
        (services_dir / "email_service.py").write_text(_gen_email_service(), encoding="utf-8")
        generated.append("email_service.py")

    if any(i in integrations for i in ("notifications", "slack")):
        (services_dir / "slack_service.py").write_text(_gen_slack_service(), encoding="utf-8")
        generated.append("slack_service.py")

    if "storage" in integrations or "s3" in integrations:
        (services_dir / "storage_service.py").write_text(_gen_storage_service(), encoding="utf-8")
        generated.append("storage_service.py")

    if integrations:
        (services_dir / "notifications.py").write_text(_gen_notifications(integrations), encoding="utf-8")
        generated.append("notifications.py")


def _generate_api_clients(spec: DoqlSpec, services_dir: pathlib.Path, generated: list[str]) -> None:
    """Generate API client files."""
    for client in spec.api_clients:
        fname = f"client_{client.name}.py"
        (services_dir / fname).write_text(_gen_api_client(client), encoding="utf-8")
        generated.append(fname)


def _generate_webhooks(spec: DoqlSpec, services_dir: pathlib.Path, generated: list[str]) -> None:
    """Generate webhook dispatcher file."""
    if spec.webhooks:
        (services_dir / "webhooks.py").write_text(_gen_webhook_dispatcher(spec.webhooks), encoding="utf-8")
        generated.append("webhooks.py")


def generate(spec: DoqlSpec, env_vars: dict[str, str], out: pathlib.Path) -> None:
    """Generate integration service modules."""
    integrations = [i.name.lower() for i in spec.integrations]
    has_content = integrations or spec.api_clients or spec.webhooks
    if not has_content:
        return

    services_dir = _setup_services_dir(out)
    generated = []

    _generate_integration_services(integrations, services_dir, generated)
    _generate_api_clients(spec, services_dir, generated)
    _generate_webhooks(spec, services_dir, generated)

    for f in generated:
        print(f"    → services/{f}")
