"""Generate PWA / mobile shell from DoqlSpec."""
from __future__ import annotations

import pathlib

from ..parser import DoqlSpec


def generate(spec: DoqlSpec, env_vars: dict[str, str], out: pathlib.Path) -> None:
    """Generate mobile layer files into *out* directory."""
    readme = out / "README.md"
    readme.write_text(
        f"# {spec.app_name} — Mobile (PWA)\n\n"
        f"Generated by `doql build`.\n",
        encoding="utf-8",
    )
    # TODO: Faza 2 — service worker, offline sync, camera API
    print(f"    → {readme.relative_to(out.parent)} (stub)")
