"""Generate PWA / mobile shell from DoqlSpec.

Produces a self-contained installable PWA:
  build/mobile/
  ├── index.html          — mobile-first shell
  ├── manifest.json       — PWA metadata
  ├── service-worker.js   — offline cache + background sync
  ├── app.js              — entity CRUD client
  ├── style.css           — mobile-first styles
  ├── icons/              — (stub) SVG icons
  └── README.md

The PWA auto-detects a running API (same origin or env.API_HOST) and
renders a simple list/detail view per ENTITY.
"""
from __future__ import annotations

import json
import pathlib
import textwrap

from ..parser import DoqlSpec
from ..utils.naming import slug


def _gen_manifest(spec: DoqlSpec) -> str:
    slug_name = slug(spec.app_name)
    return json.dumps({
        "name": spec.app_name,
        "short_name": spec.app_name[:12],
        "description": f"Generated by doql v{spec.version}",
        "start_url": "./",
        "scope": "./",
        "display": "standalone",
        "orientation": "portrait",
        "background_color": "#0f172a",
        "theme_color": "#0ea5e9",
        "icons": [
            {"src": "icons/icon-192.svg", "sizes": "192x192", "type": "image/svg+xml", "purpose": "any"},
            {"src": "icons/icon-512.svg", "sizes": "512x512", "type": "image/svg+xml", "purpose": "any maskable"},
        ],
        "id": f"doql-{slug_name}",
        "categories": ["productivity", "utilities"],
    }, indent=2)


def _gen_service_worker(spec: DoqlSpec) -> str:
    slug_name = slug(spec.app_name)
    return textwrap.dedent(f"""\
        // Service worker for {spec.app_name}
        // Generated by doql — cache-first for shell, network-first for API.
        const CACHE = "doql-{slug_name}-v{spec.version}";
        const SHELL = [
          "./",
          "./index.html",
          "./app.js",
          "./style.css",
          "./manifest.json",
        ];

        self.addEventListener("install", (e) => {{
          self.skipWaiting();
          e.waitUntil(caches.open(CACHE).then((c) => c.addAll(SHELL)));
        }});

        self.addEventListener("activate", (e) => {{
          e.waitUntil(
            caches.keys().then((keys) =>
              Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)))
            )
          );
          self.clients.claim();
        }});

        self.addEventListener("fetch", (e) => {{
          const url = new URL(e.request.url);
          // API calls — network first, fallback to cache
          if (url.pathname.startsWith("/api/") || url.pathname.startsWith("/auth/")) {{
            e.respondWith(
              fetch(e.request).then((r) => {{
                const copy = r.clone();
                caches.open(CACHE).then((c) => c.put(e.request, copy));
                return r;
              }}).catch(() => caches.match(e.request))
            );
            return;
          }}
          // Shell — cache first
          e.respondWith(
            caches.match(e.request).then((cached) => cached || fetch(e.request))
          );
        }});
        """)


def _gen_index_html(spec: DoqlSpec) -> str:
    entities = [e.name for e in spec.entities]
    return textwrap.dedent(f"""\
        <!doctype html>
        <html lang="en">
        <head>
          <meta charset="utf-8" />
          <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
          <meta name="theme-color" content="#0ea5e9" />
          <title>{spec.app_name}</title>
          <link rel="manifest" href="./manifest.json" />
          <link rel="stylesheet" href="./style.css" />
          <link rel="icon" type="image/svg+xml" href="./icons/icon-192.svg" />
        </head>
        <body>
          <header class="app-bar">
            <h1>{spec.app_name}</h1>
            <span id="status" class="status-chip">offline</span>
          </header>
          <nav class="tabs" id="tabs">
            {"".join(f'<button data-entity="{e}">{e}</button>' for e in entities) or '<em>No entities defined</em>'}
          </nav>
          <main id="list" class="list"></main>
          <button class="fab" id="fab-new" title="Create">+</button>
          <dialog id="form-dialog"><form id="entity-form" method="dialog"></form></dialog>
          <footer>
            <small>doql mobile · v{spec.version}</small>
          </footer>
          <script src="./app.js"></script>
        </body>
        </html>
        """)


def _gen_app_js(spec: DoqlSpec) -> str:
    entities_meta = [
        {
            "name": e.name,
            "path": f"/api/v1/{e.name.lower()}s",
            "fields": [{"name": f.name, "type": f.type, "required": f.required} for f in e.fields],
        }
        for e in spec.entities
    ]
    return textwrap.dedent(f"""\
        // {spec.app_name} — mobile PWA client (generated by doql)
        "use strict";

        const ENTITIES = {json.dumps(entities_meta, indent=2)};
        const API_BASE = (window.DOQL_API_BASE || "").replace(/\\/$/, "");
        const $status = document.getElementById("status");
        const $tabs = document.getElementById("tabs");
        const $list = document.getElementById("list");
        const $fab = document.getElementById("fab-new");
        const $dialog = document.getElementById("form-dialog");
        const $form = document.getElementById("entity-form");

        let current = ENTITIES[0] || null;

        function setStatus(ok) {{
          $status.textContent = ok ? "online" : "offline";
          $status.className = "status-chip " + (ok ? "ok" : "off");
        }}

        async function fetchJson(path, opts = {{}}) {{
          const r = await fetch(API_BASE + path, {{
            headers: {{ "Content-Type": "application/json" }},
            ...opts,
          }});
          if (!r.ok) throw new Error(r.status + " " + r.statusText);
          return r.status === 204 ? null : r.json();
        }}

        async function loadList() {{
          if (!current) {{ $list.innerHTML = "<em>No entities defined.</em>"; return; }}
          $list.innerHTML = "<em>Loading…</em>";
          try {{
            const items = await fetchJson(current.path);
            setStatus(true);
            $list.innerHTML = items.length
              ? items.map(renderCard).join("")
              : "<em>No records yet. Tap + to create one.</em>";
          }} catch (err) {{
            setStatus(false);
            $list.innerHTML = `<div class="err">API unreachable: ${{err.message}}</div>`;
          }}
        }}

        function renderCard(item) {{
          const title = item.name || item.title || item.email || item.id || "(untitled)";
          const subtitle = Object.entries(item)
            .filter(([k]) => !["id","name","title","email"].includes(k))
            .slice(0, 2)
            .map(([k,v]) => `${{k}}: ${{JSON.stringify(v)}}`)
            .join(" · ");
          return `<article class="card">
            <h3>${{String(title)}}</h3>
            <p>${{subtitle}}</p>
            <button class="del" data-id="${{item.id}}">delete</button>
          </article>`;
        }}

        $tabs.addEventListener("click", (e) => {{
          const btn = e.target.closest("button[data-entity]");
          if (!btn) return;
          current = ENTITIES.find((x) => x.name === btn.dataset.entity);
          document.querySelectorAll("#tabs button").forEach((b) => b.classList.toggle("active", b === btn));
          loadList();
        }});

        $list.addEventListener("click", async (e) => {{
          const del = e.target.closest("button.del");
          if (!del || !current) return;
          try {{
            await fetchJson(current.path + "/" + del.dataset.id, {{ method: "DELETE" }});
            loadList();
          }} catch (err) {{ alert("Delete failed: " + err.message); }}
        }});

        $fab.addEventListener("click", () => {{
          if (!current) return;
          $form.innerHTML = current.fields
            .filter((f) => !["id"].includes(f.name) && !f.name.endsWith("_at"))
            .map((f) => `<label>${{f.name}}<input name="${{f.name}}" ${{f.required ? "required" : ""}} /></label>`)
            .join("") + `<menu><button value="cancel">Cancel</button><button value="ok" type="submit">Save</button></menu>`;
          $dialog.showModal();
        }});

        $form.addEventListener("submit", async (e) => {{
          e.preventDefault();
          if (!current) return;
          const data = Object.fromEntries(new FormData($form).entries());
          try {{
            await fetchJson(current.path, {{ method: "POST", body: JSON.stringify(data) }});
            $dialog.close();
            loadList();
          }} catch (err) {{ alert("Create failed: " + err.message); }}
        }});

        // Activate first tab
        const first = $tabs.querySelector("button[data-entity]");
        if (first) first.classList.add("active");

        if ("serviceWorker" in navigator) {{
          navigator.serviceWorker.register("./service-worker.js").catch(console.warn);
        }}

        loadList();
        """)


def _gen_style_css() -> str:
    return textwrap.dedent("""\
        * { box-sizing: border-box; }
        body {
          margin: 0;
          font-family: system-ui, -apple-system, sans-serif;
          background: #0f172a;
          color: #e2e8f0;
          min-height: 100vh;
          display: flex;
          flex-direction: column;
          padding-top: env(safe-area-inset-top);
        }
        .app-bar {
          display: flex;
          justify-content: space-between;
          align-items: center;
          padding: 1rem;
          background: #0ea5e9;
          color: white;
          position: sticky;
          top: 0;
          z-index: 10;
        }
        .app-bar h1 { margin: 0; font-size: 1.1rem; }
        .status-chip {
          font-size: 0.75rem;
          padding: 0.2rem 0.6rem;
          border-radius: 999px;
          background: rgba(255,255,255,0.2);
        }
        .status-chip.ok { background: #10b981; }
        .status-chip.off { background: #ef4444; }
        .tabs {
          display: flex;
          gap: 0.25rem;
          padding: 0.5rem;
          overflow-x: auto;
          background: #1e293b;
          border-bottom: 1px solid #334155;
        }
        .tabs button {
          background: transparent;
          color: #94a3b8;
          border: 1px solid #334155;
          padding: 0.4rem 0.9rem;
          border-radius: 999px;
          font-size: 0.85rem;
          white-space: nowrap;
        }
        .tabs button.active {
          background: #0ea5e9;
          color: white;
          border-color: #0ea5e9;
        }
        .list {
          flex: 1;
          padding: 1rem;
          display: grid;
          gap: 0.75rem;
          overflow-y: auto;
        }
        .card {
          background: #1e293b;
          padding: 0.9rem;
          border-radius: 0.75rem;
          border: 1px solid #334155;
        }
        .card h3 { margin: 0 0 0.25rem; font-size: 1rem; }
        .card p { margin: 0; color: #94a3b8; font-size: 0.8rem; }
        .card .del {
          margin-top: 0.5rem;
          font-size: 0.75rem;
          background: transparent;
          color: #ef4444;
          border: 1px solid #ef4444;
          padding: 0.2rem 0.6rem;
          border-radius: 0.25rem;
        }
        .err {
          background: #7f1d1d;
          color: #fecaca;
          padding: 0.75rem;
          border-radius: 0.5rem;
        }
        .fab {
          position: fixed;
          right: 1.25rem;
          bottom: calc(1.25rem + env(safe-area-inset-bottom));
          width: 3.5rem;
          height: 3.5rem;
          border-radius: 50%;
          background: #0ea5e9;
          color: white;
          font-size: 1.75rem;
          border: none;
          box-shadow: 0 8px 24px rgba(14,165,233,0.4);
        }
        dialog {
          border: none;
          border-radius: 1rem;
          background: #1e293b;
          color: #e2e8f0;
          padding: 1.25rem;
          width: 90vw;
          max-width: 24rem;
        }
        dialog::backdrop { background: rgba(15,23,42,0.75); }
        dialog label {
          display: block;
          margin: 0.5rem 0;
          font-size: 0.85rem;
          color: #94a3b8;
        }
        dialog input {
          width: 100%;
          padding: 0.5rem;
          margin-top: 0.25rem;
          background: #0f172a;
          color: white;
          border: 1px solid #334155;
          border-radius: 0.35rem;
        }
        dialog menu {
          display: flex;
          gap: 0.5rem;
          justify-content: flex-end;
          margin: 1rem 0 0;
          padding: 0;
        }
        dialog menu button {
          padding: 0.5rem 1rem;
          border-radius: 0.35rem;
          border: 1px solid #334155;
          background: #0ea5e9;
          color: white;
        }
        dialog menu button[value="cancel"] {
          background: transparent;
          color: #94a3b8;
        }
        footer {
          text-align: center;
          padding: 0.75rem;
          color: #64748b;
          font-size: 0.75rem;
        }
        """)


def _gen_icons(out: pathlib.Path, spec: DoqlSpec) -> None:
    icons_dir = out / "icons"
    icons_dir.mkdir(exist_ok=True)
    letter = (spec.app_name or "D")[0].upper()
    for size in (192, 512):
        svg = textwrap.dedent(f"""\
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {size} {size}">
              <rect width="{size}" height="{size}" rx="{size // 5}" fill="#0ea5e9"/>
              <text x="50%" y="54%" text-anchor="middle"
                    font-family="system-ui, sans-serif"
                    font-size="{int(size * 0.55)}" font-weight="700"
                    fill="white" dominant-baseline="middle">{letter}</text>
            </svg>
            """)
        (icons_dir / f"icon-{size}.svg").write_text(svg, encoding="utf-8")


def generate(spec: DoqlSpec, env_vars: dict[str, str], out: pathlib.Path) -> None:
    """Generate mobile PWA into *out* directory."""
    # Skip generation if no mobile interface is declared
    mobile_iface = next((i for i in spec.interfaces if i.type in ("pwa", "mobile", "mobile-pwa")), None)
    if not mobile_iface and not spec.entities:
        (out / "README.md").write_text(
            f"# {spec.app_name} — Mobile\n\n"
            "No mobile/PWA interface declared and no entities — skipping.\n",
            encoding="utf-8",
        )
        print("    → mobile/README.md (skipped)")
        return

    out.mkdir(parents=True, exist_ok=True)
    (out / "manifest.json").write_text(_gen_manifest(spec), encoding="utf-8")
    (out / "service-worker.js").write_text(_gen_service_worker(spec), encoding="utf-8")
    (out / "index.html").write_text(_gen_index_html(spec), encoding="utf-8")
    (out / "app.js").write_text(_gen_app_js(spec), encoding="utf-8")
    (out / "style.css").write_text(_gen_style_css(), encoding="utf-8")
    _gen_icons(out, spec)

    (out / "README.md").write_text(
        f"# {spec.app_name} — Mobile (PWA)\n\n"
        f"Generated by `doql build`. Installable PWA with offline support.\n\n"
        f"## Quick start\n\n"
        f"```bash\n"
        f"cd build/mobile\n"
        f"# Serve over HTTP (service worker requires http/https, not file://)\n"
        f"python3 -m http.server 8090\n"
        f"# Open http://localhost:8090/ in Chrome/Firefox\n"
        f"# On Android: 'Install app' from the address bar menu.\n"
        f"```\n\n"
        f"## Connecting to the API\n\n"
        f"By default the PWA calls `/api/v1/...` on the same origin. To point\n"
        f"at a different API (e.g. during development), set before loading app.js:\n\n"
        f"```html\n<script>window.DOQL_API_BASE = 'http://localhost:8000';</script>\n```\n\n"
        f"## Production\n\n"
        f"Serve `build/mobile/` behind the same Traefik / nginx that hosts the API,\n"
        f"so `/api/v1` is same-origin and offline cache works as expected.\n",
        encoding="utf-8",
    )
    print("    → mobile/manifest.json")
    print("    → mobile/service-worker.js")
    print("    → mobile/index.html, app.js, style.css")
    print("    → mobile/icons/icon-192.svg, icon-512.svg")
    print("    → mobile/README.md")
