"""Generate report pipeline from REPORT definitions.

Produces:
  build/reports/
  ├── generate_<report>.py   — standalone script to query + render + deliver
  └── README.md
"""
from __future__ import annotations

import pathlib
import textwrap

from ..parser import DoqlSpec, Report


def _gen_report_script(rpt: Report, spec: DoqlSpec) -> str:
    """Generate a standalone report script."""
    schedule_comment = f"# Schedule: {rpt.schedule}" if rpt.schedule else "# No schedule — manual run"
    recipients_str = ", ".join(
        f'"{k}"' for k in rpt.recipients.keys()
    ) if rpt.recipients else '"admin@example.com"'
    retention = rpt.retention or "90d"

    return textwrap.dedent(f'''\
        #!/usr/bin/env python3
        """{rpt.name} report — generated by doql build.

        {schedule_comment}
        Output: {rpt.output}

        Usage:
            python generate_{rpt.name}.py [--send] [--output FILE]

        Requires:
            pip install jinja2 weasyprint   # for PDF
        """
        import argparse
        import json
        import pathlib
        import sys
        from datetime import datetime

        REPORT_NAME = "{rpt.name}"
        OUTPUT_TYPE = "{rpt.output}"
        SCHEDULE = "{rpt.schedule or 'manual'}"
        RETENTION = "{retention}"
        RECIPIENTS = [{recipients_str}]

        PROJECT_ROOT = pathlib.Path(__file__).resolve().parent.parent.parent


        def query_data() -> dict:
            """Query data for the report — integrate with your data sources."""
            return {{
                "report_name": REPORT_NAME,
                "generated_at": datetime.now().isoformat(),
                "app_name": "{spec.app_name}",
                "version": "{spec.version}",
                "data": [],  # TODO: connect to DATA sources
            }}


        def render(data: dict, output_path: pathlib.Path):
            """Render the report to file."""
            template_path = PROJECT_ROOT / "{rpt.template or ''}"

            if OUTPUT_TYPE == "pdf" and template_path.exists():
                try:
                    from jinja2 import Environment, FileSystemLoader
                    from weasyprint import HTML
                    env = Environment(loader=FileSystemLoader(str(template_path.parent)))
                    tmpl = env.get_template(template_path.name)
                    html = tmpl.render(**data)
                    HTML(string=html).write_pdf(str(output_path))
                    print(f"PDF → {{output_path}}")
                    return
                except ImportError as e:
                    print(f"Missing dependency: {{e}}", file=sys.stderr)

            # Fallback: JSON
            output_path = output_path.with_suffix(".json")
            output_path.write_text(json.dumps(data, indent=2, default=str), encoding="utf-8")
            print(f"JSON → {{output_path}}")


        def send_report(path: pathlib.Path):
            """Send report to recipients (stub — integrate with SMTP/Slack)."""
            print(f"Would send {{path}} to: {{', '.join(RECIPIENTS)}}")
            # TODO: integrate with email/Slack from INTEGRATION section


        def main():
            parser = argparse.ArgumentParser(description=f"Generate {{REPORT_NAME}} report")
            parser.add_argument("--send", action="store_true", help="Send to recipients")
            parser.add_argument("-o", "--output", help="Output file path")
            args = parser.parse_args()

            data = query_data()
            out = pathlib.Path(args.output or f"{{REPORT_NAME}}_{{datetime.now().strftime('%Y%m%d')}}.{{OUTPUT_TYPE}}")
            render(data, out)

            if args.send:
                send_report(out)


        if __name__ == "__main__":
            main()
    ''')


def generate(spec: DoqlSpec, env_vars: dict[str, str], out: pathlib.Path) -> None:
    """Generate report scripts into *out* directory."""
    if not spec.reports:
        print(f"    → reports/ (no REPORTs defined, skipped)")
        return

    for rpt in spec.reports:
        script = out / f"generate_{rpt.name}.py"
        script.write_text(_gen_report_script(rpt, spec), encoding="utf-8")
        print(f"    → reports/generate_{rpt.name}.py")

    # cron / schedule helper
    schedules = [(r.name, r.schedule) for r in spec.reports if r.schedule]
    if schedules:
        crontab_lines = ["# Generated crontab entries for doql reports"]
        for name, sched in schedules:
            crontab_lines.append(f"{sched}  cd /opt/app && python reports/generate_{name}.py --send")
        crontab_lines.append("")
        (out / "crontab").write_text("\n".join(crontab_lines), encoding="utf-8")
        print(f"    → reports/crontab")

    (out / "README.md").write_text(
        f"# {spec.app_name} — Reports\n\n"
        f"Generated by `doql build`.\n\n"
        + "\n".join(
            f"- **{r.name}** ({r.output}) schedule=`{r.schedule or 'manual'}`"
            for r in spec.reports
        )
        + "\n",
        encoding="utf-8",
    )
    print(f"    → reports/README.md")
