"""Generate Vite / frontend tooling configuration files.

Produces:
  web/vite.config.ts      — Vite TypeScript config
  web/tsconfig.json       — TypeScript compiler options
  web/index.html          — SPA entry point
"""
from __future__ import annotations

import pathlib
import textwrap

from ..parser import DoqlSpec
from ..utils.naming import slug


def _gen_vite_config(spec: DoqlSpec, env_vars: dict[str, str], out: pathlib.Path) -> None:
    """Generate vite.config.ts for a Vite-based SPA."""
    slug = slug(spec.app_name)
    port = env_vars.get("VITE_PORT", "5173")
    api_proxy = env_vars.get("VITE_API_PROXY", "/api")
    api_target = env_vars.get("VITE_API_TARGET", "http://localhost:8000")

    config = textwrap.dedent(f'''\
        // Generated by doql build — Vite configuration
        import {{ defineConfig }} from 'vite';
        import react from '@vitejs/plugin-react';
        import {{ resolve }} from 'path';

        export default defineConfig({{
          plugins: [react()],
          resolve: {{
            alias: {{
              '@': resolve(__dirname, './src'),
            }},
          }},
          server: {{
            port: {port},
            proxy: {{
              '{api_proxy}': {{
                target: '{api_target}',
                changeOrigin: true,
                secure: false,
              }},
            }},
          }},
          build: {{
            outDir: 'dist',
            sourcemap: true,
            rollupOptions: {{
              input: {{
                main: resolve(__dirname, 'index.html'),
              }},
            }},
          }},
        }});
    ''')
    (out / "vite.config.ts").write_text(config, encoding="utf-8")
    print(f"    → web/vite.config.ts")


def _gen_tsconfig(spec: DoqlSpec, out: pathlib.Path) -> None:
    """Generate tsconfig.json."""
    tsconfig = textwrap.dedent("""\
        {
          "compilerOptions": {
            "target": "ES2020",
            "useDefineForClassFields": true,
            "lib": ["ES2020", "DOM", "DOM.Iterable"],
            "module": "ESNext",
            "skipLibCheck": true,
            "moduleResolution": "bundler",
            "allowImportingTsExtensions": true,
            "resolveJsonModule": true,
            "isolatedModules": true,
            "noEmit": true,
            "jsx": "react-jsx",
            "strict": true,
            "noUnusedLocals": true,
            "noUnusedParameters": true,
            "noFallthroughCasesInSwitch": true,
            "baseUrl": ".",
            "paths": {
              "@/*": ["./src/*"]
            }
          },
          "include": ["src"],
          "references": [{ "path": "./tsconfig.node.json" }]
        }
    """)
    (out / "tsconfig.json").write_text(tsconfig, encoding="utf-8")
    print(f"    → web/tsconfig.json")


def _gen_index_html(spec: DoqlSpec, out: pathlib.Path) -> None:
    """Generate index.html SPA entry point."""
    slug = slug(spec.app_name)
    html = textwrap.dedent(f'''\
        <!DOCTYPE html>
        <html lang="en">
          <head>
            <meta charset="UTF-8" />
            <link rel="icon" type="image/svg+xml" href="/vite.svg" />
            <meta name="viewport" content="width=device-width, initial-scale=1.0" />
            <title>{spec.app_name}</title>
          </head>
          <body>
            <div id="root"></div>
            <script type="module" src="/src/main.tsx"></script>
          </body>
        </html>
    ''')
    (out / "index.html").write_text(html, encoding="utf-8")
    print(f"    → web/index.html")


def generate(spec: DoqlSpec, env_vars: dict[str, str], out: pathlib.Path) -> None:
    """Generate Vite tooling config into *out* directory."""
    _gen_vite_config(spec, env_vars, out)
    _gen_tsconfig(spec, out)
    _gen_index_html(spec, out)
