"""Generate React + Vite frontend from DoqlSpec."""
from __future__ import annotations

import pathlib

from ..parser import DoqlSpec


def generate(spec: DoqlSpec, env_vars: dict[str, str], out: pathlib.Path) -> None:
    """Generate web layer files into *out* directory."""
    readme = out / "README.md"
    readme.write_text(
        f"# {spec.app_name} — Web\n\n"
        f"Generated by `doql build`.\n\n"
        f"Interfaces: {', '.join(i.name for i in spec.interfaces if i.name == 'web')}\n",
        encoding="utf-8",
    )
    # TODO: Faza 1 — React pages, components, routing, i18n
    print(f"    → {readme.relative_to(out.parent)} (stub)")
