"""Generate workflow engine from WORKFLOW definitions.

Produces:
  build/api/workflows/
  ├── __init__.py
  ├── engine.py            — state-machine runner + event dispatcher
  ├── <workflow_name>.py   — per-workflow implementation
  └── scheduler.py         — cron-triggered workflow launcher
"""
from __future__ import annotations

import pathlib
import textwrap

from ..parser import DoqlSpec, Workflow, WorkflowStep
from ..utils.naming import snake as _snake


def _gen_engine() -> str:
    return textwrap.dedent('''\
        """Workflow engine — generated by doql.

        Lightweight state-machine runner with event dispatch.
        """
        from __future__ import annotations

        import logging
        from dataclasses import dataclass, field
        from enum import Enum
        from typing import Any, Callable, Optional

        logger = logging.getLogger("workflow.engine")


        class StepStatus(str, Enum):
            PENDING = "pending"
            RUNNING = "running"
            COMPLETED = "completed"
            FAILED = "failed"
            SKIPPED = "skipped"


        @dataclass
        class Step:
            name: str
            action: Callable
            status: StepStatus = StepStatus.PENDING
            result: Any = None
            error: Optional[str] = None


        @dataclass
        class WorkflowRun:
            workflow_name: str
            steps: list[Step] = field(default_factory=list)
            context: dict[str, Any] = field(default_factory=dict)
            status: StepStatus = StepStatus.PENDING

            @property
            def current_step(self) -> Optional[Step]:
                for s in self.steps:
                    if s.status in (StepStatus.PENDING, StepStatus.RUNNING):
                        return s
                return None


        class WorkflowEngine:
            """Execute workflows step-by-step with error handling."""

            def __init__(self):
                self._registry: dict[str, Callable] = {}
                self._event_handlers: dict[str, list[str]] = {}

            def register(self, name: str, factory: Callable):
                self._registry[name] = factory

            def on_event(self, event: str, workflow_name: str):
                self._event_handlers.setdefault(event, []).append(workflow_name)

            def trigger_event(self, event: str, payload: dict | None = None):
                workflows = self._event_handlers.get(event, [])
                results = []
                for wf_name in workflows:
                    result = self.run(wf_name, context=payload or {})
                    results.append(result)
                return results

            def run(self, name: str, context: dict | None = None) -> WorkflowRun:
                if name not in self._registry:
                    raise ValueError(f"Unknown workflow: {name}")

                run = self._registry[name](context or {})
                run.status = StepStatus.RUNNING
                logger.info(f"Starting workflow: {name}")

                for step in run.steps:
                    step.status = StepStatus.RUNNING
                    try:
                        step.result = step.action(run.context)
                        step.status = StepStatus.COMPLETED
                        logger.info(f"  Step '{step.name}': completed")
                    except Exception as e:
                        step.status = StepStatus.FAILED
                        step.error = str(e)
                        logger.error(f"  Step '{step.name}': FAILED — {e}")
                        run.status = StepStatus.FAILED
                        # Skip remaining steps
                        for remaining in run.steps:
                            if remaining.status == StepStatus.PENDING:
                                remaining.status = StepStatus.SKIPPED
                        return run

                run.status = StepStatus.COMPLETED
                logger.info(f"Workflow '{name}': completed ({len(run.steps)} steps)")
                return run


        # Global engine instance
        engine = WorkflowEngine()
    ''')


def _step_fn_name(action: str) -> str:
    """Create a valid Python function name from a workflow step action."""
    import re
    name = action.replace(".", "_").replace(" ", "_")
    # Remove any characters that aren't valid in Python identifiers
    name = re.sub(r'[^a-zA-Z0-9_]', '_', name)
    # Collapse multiple underscores
    name = re.sub(r'_+', '_', name).strip('_')
    return _snake(name)


def _gen_workflow_module(wf: Workflow, spec: DoqlSpec) -> str:
    """Generate a workflow implementation module."""
    steps_code = []
    for i, step in enumerate(wf.steps):
        step_name = _step_fn_name(step.action)
        steps_code.append(
            f'    Step(\n'
            f'        name={repr(step.action)},\n'
            f'        action=lambda ctx: step_{step_name}(ctx),\n'
            f'    ),'
        )

    step_functions = []
    for step in wf.steps:
        step_name = _step_fn_name(step.action)
        target_comment = f"  # target: {step.target}" if step.target else ""
        step_functions.append(
            f'def step_{step_name}(ctx: dict):{target_comment}\n'
            f"    '''Action: {step.action}'''\n"
            f'    # TODO: implement {step.action.replace(chr(34), chr(39))}\n'
            f'    pass\n'
        )

    trigger_comment = ""
    if wf.trigger:
        trigger_comment = f"# Trigger: {wf.trigger}\n"
    if wf.schedule:
        trigger_comment += f"# Schedule: {wf.schedule}\n"
    if wf.condition:
        trigger_comment += f"# Condition: {wf.condition}\n"

    return (
        f'"""Workflow: {wf.name} — generated by doql."""\n'
        f'from workflows.engine import WorkflowRun, Step, engine\n'
        f'\n'
        f'{trigger_comment}\n'
        + "\n".join(step_functions)
        + "\n\n"
        f'def create(context: dict) -> WorkflowRun:\n'
        f'    return WorkflowRun(\n'
        f'        workflow_name="{wf.name}",\n'
        f'        context=context,\n'
        f'        steps=[\n'
        + "\n".join(steps_code)
        + "\n"
        f'        ],\n'
        f'    )\n'
        f'\n'
        f'\n'
        f'# Register with engine\n'
        f'engine.register("{wf.name}", create)\n'
    )


def _extract_cron(sched: str) -> str:
    """Extract bare cron expression from a schedule string like 'schedule \"0 8 * * *\"'."""
    if sched and sched.startswith("schedule"):
        import re as _re
        m = _re.search(r'"([^"]+)"', sched)
        if m:
            return m.group(1)
    return sched


def _gen_scheduler(spec: DoqlSpec) -> str:
    """Generate a scheduler that triggers workflows on cron schedules."""
    scheduled = [
        (wf.name, wf.schedule or wf.trigger)
        for wf in spec.workflows
        if wf.schedule or (wf.trigger and wf.trigger.startswith("schedule"))
    ]
    imports = [f"import workflows.wf_{_snake(wf.name)}  # noqa: F401" for wf in spec.workflows]
    schedule_entries = [f'    ("{name}", "{_extract_cron(sched)}"),\n' for name, sched in scheduled]

    return (
        '"""Workflow scheduler — generated by doql.\n'
        '\n'
        'Usage:\n'
        '    python -m workflows.scheduler\n'
        '\n'
        'Requires: pip install schedule\n'
        '"""\n'
        'import logging\n'
        'import time\n'
        '\n'
        'from workflows.engine import engine\n'
        '\n'
        '# Import all workflows to register them\n'
        + "\n".join(imports) + "\n"
        '\n'
        'logger = logging.getLogger("workflow.scheduler")\n'
        '\n'
        'SCHEDULED_WORKFLOWS = [\n'
        + "\n".join(schedule_entries) + "\n"
        ']\n'
        '\n'
        '\n'
        'def run_scheduled():\n'
        '    """Run all scheduled workflows (integrate with your cron/schedule library)."""\n'
        '    for name, cron in SCHEDULED_WORKFLOWS:\n'
        '        logger.info(f"Running scheduled workflow: {name} ({cron})")\n'
        '        try:\n'
        '            result = engine.run(name)\n'
        '            logger.info(f"  Result: {result.status.value}")\n'
        '        except Exception as e:\n'
        '            logger.error(f"  Error: {e}")\n'
        '\n'
        '\n'
        'if __name__ == "__main__":\n'
        '    logging.basicConfig(level=logging.INFO)\n'
        '    run_scheduled()\n'
    )


def _gen_init(spec: DoqlSpec) -> str:
    lines = ['"""Workflows package — generated by doql."""']
    for wf in spec.workflows:
        lines.append(f'from workflows.wf_{_snake(wf.name)} import create as {_snake(wf.name)}  # noqa: F401')
    lines.append('')
    return '\n'.join(lines)


def _gen_routes(spec: DoqlSpec) -> str:
    """Generate FastAPI routes for triggering workflows via REST."""
    lines = [
        '"""Workflow API routes — generated by doql."""',
        'from fastapi import APIRouter',
        'from workflows.engine import engine, StepStatus',
        '',
        'router = APIRouter(prefix="/api/v1/workflows", tags=["workflows"])',
        '',
        '',
        '@router.get("/")',
        'def list_workflows():',
        '    return {"workflows": list(engine._registry.keys())}',
        '',
        '',
        '@router.post("/{name}/run")',
        'def run_workflow(name: str, context: dict | None = None):',
        '    try:',
        '        result = engine.run(name, context or {})',
        '        return {',
        '            "workflow": name,',
        '            "status": result.status.value,',
        '            "steps": [',
        '                {"name": s.name, "status": s.status.value, "error": s.error}',
        '                for s in result.steps',
        '            ],',
        '        }',
        '    except ValueError as e:',
        '        from fastapi import HTTPException',
        '        raise HTTPException(404, str(e))',
        '',
        '',
        '@router.post("/event/{event}")',
        'def trigger_event(event: str, payload: dict | None = None):',
        '    results = engine.trigger_event(event, payload)',
        '    return {"event": event, "workflows_triggered": len(results)}',
        '',
    ]
    return '\n'.join(lines)


def generate(spec: DoqlSpec, env_vars: dict[str, str], out: pathlib.Path) -> None:
    """Generate workflow engine modules."""
    if not spec.workflows:
        return

    wf_dir = out
    wf_dir.mkdir(parents=True, exist_ok=True)

    (wf_dir / "__init__.py").write_text(_gen_init(spec), encoding="utf-8")
    (wf_dir / "engine.py").write_text(_gen_engine(), encoding="utf-8")
    print(f"    → workflows/engine.py")

    for wf in spec.workflows:
        fname = f"wf_{_snake(wf.name)}.py"
        (wf_dir / fname).write_text(_gen_workflow_module(wf, spec), encoding="utf-8")
        print(f"    → workflows/{fname}")

    (wf_dir / "scheduler.py").write_text(_gen_scheduler(spec), encoding="utf-8")
    print(f"    → workflows/scheduler.py")

    (wf_dir / "routes.py").write_text(_gen_routes(spec), encoding="utf-8")
    print(f"    → workflows/routes.py")
