# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dsl2doql/v1/command.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'dsl2doql/v1/command.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x64sl2doql/v1/command.proto\x12\x0b\x64sl2doql.v1\"<\n\x0cQueryCommand\x12\x0e\n\x06target\x18\x01 \x01(\t\x12\x0c\n\x04\x66ile\x18\x02 \x01(\t\x12\x0e\n\x06\x66ormat\x18\x03 \x01(\t\"\x1f\n\x0fValidateCommand\x12\x0c\n\x04path\x18\x01 \x01(\t\",\n\x0eResolveCommand\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0c\n\x04\x66ile\x18\x02 \x01(\t\"?\n\x0cPatchCommand\x12\x0e\n\x06target\x18\x01 \x01(\t\x12\x11\n\twith_path\x18\x02 \x01(\t\x12\x0c\n\x04\x66ile\x18\x03 \x01(\t\",\n\x0fGenerateCommand\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0b\n\x03out\x18\x02 \x01(\t\")\n\x0c\x41\x64optCommand\x12\x0c\n\x04root\x18\x01 \x01(\t\x12\x0b\n\x03out\x18\x02 \x01(\t\"@\n\x12MaterializeCommand\x12\x0e\n\x06target\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x65st\x18\x02 \x01(\t\x12\x0c\n\x04\x66ile\x18\x03 \x01(\t\"-\n\x0e\x43onvertCommand\x12\x0e\n\x06source\x18\x01 \x01(\t\x12\x0b\n\x03out\x18\x02 \x01(\t\"\xd1\x03\n\x0b\x44slEnvelope\x12\x0c\n\x04verb\x18\x01 \x01(\t\x12*\n\x05query\x18\n \x01(\x0b\x32\x19.dsl2doql.v1.QueryCommandH\x00\x12\x30\n\x08validate\x18\x0b \x01(\x0b\x32\x1c.dsl2doql.v1.ValidateCommandH\x00\x12.\n\x07resolve\x18\x0c \x01(\x0b\x32\x1b.dsl2doql.v1.ResolveCommandH\x00\x12*\n\x05patch\x18\r \x01(\x0b\x32\x19.dsl2doql.v1.PatchCommandH\x00\x12\x30\n\x08generate\x18\x0e \x01(\x0b\x32\x1c.dsl2doql.v1.GenerateCommandH\x00\x12*\n\x05\x61\x64opt\x18\x0f \x01(\x0b\x32\x19.dsl2doql.v1.AdoptCommandH\x00\x12\x36\n\x0bmaterialize\x18\x10 \x01(\x0b\x32\x1f.dsl2doql.v1.MaterializeCommandH\x00\x12.\n\x07\x63onvert\x18\x11 \x01(\x0b\x32\x1b.dsl2doql.v1.ConvertCommandH\x00\x12\x14\n\x0c\x64\x65\x66\x61ult_file\x18\x14 \x01(\t\x12\x16\n\x0e\x63orrelation_id\x18\x15 \x01(\tB\x06\n\x04\x62odyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dsl2doql.v1.command_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUERYCOMMAND']._serialized_start=42
  _globals['_QUERYCOMMAND']._serialized_end=102
  _globals['_VALIDATECOMMAND']._serialized_start=104
  _globals['_VALIDATECOMMAND']._serialized_end=135
  _globals['_RESOLVECOMMAND']._serialized_start=137
  _globals['_RESOLVECOMMAND']._serialized_end=181
  _globals['_PATCHCOMMAND']._serialized_start=183
  _globals['_PATCHCOMMAND']._serialized_end=246
  _globals['_GENERATECOMMAND']._serialized_start=248
  _globals['_GENERATECOMMAND']._serialized_end=292
  _globals['_ADOPTCOMMAND']._serialized_start=294
  _globals['_ADOPTCOMMAND']._serialized_end=335
  _globals['_MATERIALIZECOMMAND']._serialized_start=337
  _globals['_MATERIALIZECOMMAND']._serialized_end=401
  _globals['_CONVERTCOMMAND']._serialized_start=403
  _globals['_CONVERTCOMMAND']._serialized_end=448
  _globals['_DSLENVELOPE']._serialized_start=451
  _globals['_DSLENVELOPE']._serialized_end=916
# @@protoc_insertion_point(module_scope)
